<?php
declare(strict_types=1);
$ownMechanicId=(int)($currentUser['mechanic_id']??0);
?>
<section class="hero panel"><div><div class="eyebrow"><?=h(roleLabel($currentUser['role']))?></div><h1>Omat tiedot</h1><p><strong><?=h($currentUser['display_name'])?></strong><?=$currentUser['display_name']!==$currentUser['username']?' · tunnus: '.h($currentUser['username']):''?></p><div class="sub"><?=h(roleLabel($currentUser['role']))?><?=!empty($currentUser['last_login_at'])?' · viimeisin kirjautuminen '.h(date('d.m.Y H:i',strtotime((string)$currentUser['last_login_at']))):''?></div></div></section>
<?php if(mechanicsEnabled($app)&&!(int)$currentUser['force_password_change']):?>
<section class="section panel"><h2>Oletusmekaanikko</h2><form method="post" class="account-mech"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="update_own_mechanic"><div class="grid grid3"><div><label>Mekaanikko, joka valitaan uuteen huoltoon sinulle</label><select name="mechanic_id"><option value="0">Korjaamon oletus / ei kytkentää</option><?php foreach($activeMechanics as $m):?><option value="<?=(int)$m['id']?>" <?=$ownMechanicId===(int)$m['id']?'selected':''?>><?=h($m['name'])?></option><?php endforeach;?></select></div><div style="align-self:end"><button class="btn2">Tallenna</button></div></div></form></section>
<?php endif;?>
<section class="section panel"><h2>Vaihda oma salasana</h2><?php if((int)$currentUser['force_password_change']):?><div class="flash warn">Vaihda väliaikainen salasana ennen ohjelman käyttöä.</div><?php endif;?>
<form method="post"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="change_password"><div class="grid grid3"><div><label>Nykyinen salasana</label><input type="password" name="current_password" required autocomplete="current-password"></div><div><label>Uusi salasana</label><input type="password" name="new_password" required minlength="12" autocomplete="new-password"></div><div><label>Uusi salasana uudelleen</label><input type="password" name="password_confirm" required autocomplete="new-password"></div></div><label class="show-pw"><input type="checkbox" data-show-passwords> Näytä salasanat</label><p class="tiny">Vähintään 12 merkkiä, enintään 72 tavua. Voit käyttää usean sanan lausetta. Muut kirjautumisistuntosi päättyvät vaihdon jälkeen.</p><div class="form-actions"><button class="btn">Vaihda salasana</button></div></form></section>
<?php if(!(int)$currentUser['force_password_change']):?>
<section class="section panel"><h2>Kirjautuneena muilla laitteilla?</h2><p class="tiny">Päättää kaikki muut kirjautumisistuntosi (esimerkiksi unohtunut puhelin tai työkoneen selain). Tämä istunto jatkuu.</p>
<form method="post"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="logout_others"><div class="grid grid3"><div><label>Oma nykyinen salasana</label><input type="password" name="current_password" required autocomplete="current-password"></div><div style="align-self:end"><button class="btn2">Kirjaa ulos muut istunnot</button></div></div></form></section>
<?php endif;?>
