<?php
declare(strict_types=1);
$ownMechanicId=(int)($currentUser['mechanic_id']??0);
?>
<section class="hero panel"><div><div class="eyebrow"><?=h(roleLabel($currentUser['role']))?></div><h1><?=t('acct.title')?></h1><p><strong><?=h($currentUser['display_name'])?></strong><?=$currentUser['display_name']!==$currentUser['username']?' · '.t('acct.username_line',['username'=>h($currentUser['username'])]):''?></p><div class="sub"><?=h(roleLabel($currentUser['role']))?><?=!empty($currentUser['last_login_at'])?' · '.t('acct.last_login',['date'=>h(date('d.m.Y H:i',strtotime((string)$currentUser['last_login_at'])))]):''?></div></div></section>
<?php if(mechanicsEnabled($app)&&!(int)$currentUser['force_password_change']):?>
<section class="section panel"><h2><?=t('acct.default_mechanic')?></h2><form method="post" class="account-mech"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="update_own_mechanic"><div class="grid grid3"><div><label><?=t('acct.mechanic_label')?></label><select name="mechanic_id"><option value="0"><?=t('acct.shop_default_no_link')?></option><?php foreach($activeMechanics as $m):?><option value="<?=(int)$m['id']?>" <?=$ownMechanicId===(int)$m['id']?'selected':''?>><?=h($m['name'])?></option><?php endforeach;?></select></div><div style="align-self:end"><button class="btn2"><?=t('acct.save')?></button></div></div></form></section>
<?php endif;?>
<?php $ownLang=i18nValidLanguage((string)($app['user_lang_'.(int)$currentUser['id']]??''));$sysLang=i18nValidLanguage((string)($app['language']??''))?:I18N_DEFAULT_LANG;?>
<section class="section panel"><h2><?=t('acct.language_title')?></h2><p class="tiny"><?=t('acct.language_help')?></p><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="update_own_language"><div class="grid grid3"><div><label><?=t('acct.language_label')?></label><select name="own_language"><option value=""><?=t('acct.language_system_default',['name'=>h(i18nLanguageName($sysLang))])?></option><?php foreach(i18nLanguageOptions() as $lc=>$ln):?><option value="<?=h($lc)?>" <?=$ownLang===$lc?'selected':''?>><?=h($ln)?></option><?php endforeach;?></select></div><div style="align-self:end"><button class="btn2"><?=t('acct.language_save')?></button></div></div></form></section>
<section class="section panel"><h2><?=t('acct.change_password_title')?></h2><?php if((int)$currentUser['force_password_change']):?><div class="flash warn"><?=t('acct.force_change_notice')?></div><?php endif;?>
<form method="post"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="change_password"><div class="grid grid3"><div><label><?=t('acct.current_password')?></label><input type="password" name="current_password" required autocomplete="current-password"></div><div><label><?=t('acct.new_password')?></label><input type="password" name="new_password" required minlength="12" autocomplete="new-password"></div><div><label><?=t('acct.new_password_again')?></label><input type="password" name="password_confirm" required autocomplete="new-password"></div></div><label class="show-pw"><input type="checkbox" data-show-passwords> <?=t('acct.show_passwords')?></label><p class="tiny"><?=t('acct.password_rules')?></p><div class="form-actions"><button class="btn"><?=t('acct.change_password_btn')?></button></div></form></section>
<?php if(!(int)$currentUser['force_password_change']):?>
<section class="section panel"><h2><?=t('acct.other_devices_title')?></h2><p class="tiny"><?=t('acct.other_devices_help')?></p>
<form method="post"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="logout_others"><div class="grid grid3"><div><label><?=t('acct.own_current_password')?></label><input type="password" name="current_password" required autocomplete="current-password"></div><div style="align-self:end"><button class="btn2"><?=t('acct.logout_others_btn')?></button></div></div></form></section>
<?php endif;?>
