<?php
declare(strict_types=1);
 ?>
<?php if($customer): ?>
<section class="hero panel"><div><div class="eyebrow"><?=t('cust.customer_eyebrow',['num'=>h($customer['customer_number']?:('#'.$customerId))])?></div><h1><?=h($customer['name'])?></h1><div class="sub"><?=h(customerTypeLabel((string)$customer['customer_type']))?><?=trim((string)$customer['phone'])!==''?' · '.h($customer['phone']):''?><?=trim((string)$customer['email'])!==''?' · '.h($customer['email']):''?></div></div><div class="form-actions"><a class="btn2" href="?view=customers"><?=t('cust.back_to_list')?></a></div></section>
<section class="section panel"><div class="sectionhead"><div><h2><?=t('cust.details_title')?></h2><div class="tiny"><?=t('cust.edit_note')?></div></div><span class="badge"><?=(int)$customer['active']===1?t('cust.active'):t('cust.archived')?></span></div><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="update_customer"><?php editField($db,'customer',$customerId);?><input type="hidden" name="customer_id" value="<?=$customerId?>"><div class="grid grid4"><div><label><?=t('cust.number')?></label><input name="customer_number" value="<?=h($customer['customer_number'])?>"></div><div><label><?=t('cust.type')?></label><select name="customer_type"><option value="private" <?=$customer['customer_type']==='private'?'selected':''?>><?=t('cust.type_private')?></option><option value="company" <?=$customer['customer_type']==='company'?'selected':''?>><?=t('cust.type_company')?></option></select></div><div><label><?=t('cust.name')?></label><input name="customer_name" value="<?=h($customer['name'])?>" required></div><div><label><?=t('cust.contact')?></label><input name="contact_name" value="<?=h($customer['contact_name'])?>"></div><div><label><?=t('cust.phone')?></label><input name="phone" value="<?=h($customer['phone'])?>"></div><div><label><?=t('cust.email')?></label><input name="email" value="<?=h($customer['email'])?>"></div><div><label><?=t('cust.street')?></label><input name="address" value="<?=h($customer['address'])?>"></div><div><label><?=t('cust.postal_code')?></label><input name="postal_code" value="<?=h($customer['postal_code'])?>"></div><div><label><?=t('cust.city')?></label><input name="city" value="<?=h($customer['city'])?>"></div><div><label><?=t('cust.business_id')?></label><input name="business_id" value="<?=h($customer['business_id'])?>"></div><div><label style="margin-top:28px"><input type="checkbox" name="customer_active" value="1" <?=(int)$customer['active']===1?'checked':''?>> <?=t('cust.active')?></label></div><div><label><?=t('cust.notes')?></label><textarea name="customer_notes"><?=h($customer['notes'])?></textarea></div></div><div class="form-actions"><button class="btn"><?=t('cust.save')?></button></div></form></section>
<section class="section panel dangerzone"><details class="clean"><summary><?=t('cust.delete_summary')?></summary><div class="inside">
<div class="flash warn"><?=t('cust.delete_warning')?></div>
<?php if(!canAction('delete_customer')):?>
<p class="tiny"><?=t('cust.delete_admin_only')?></p>
<?php elseif(customerDeleteAllowed($customerDeleteRefs)):?>
<form method="post" onsubmit="return confirm('<?=t('cust.delete_confirm')?>');"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="delete_customer"><input type="hidden" name="customer_id" value="<?=$customerId?>"><input type="hidden" name="delete_confirm" value="1"><button class="danger" type="submit"><?=t('cust.delete_btn')?></button></form>
<p class="tiny"><?=t('cust.delete_no_refs')?></p>
<?php else:?>
<p class="tiny"><?=t('cust.delete_blocked',['cars'=>$customerDeleteRefs['cars'],'history'=>$customerDeleteRefs['history'],'services'=>$customerDeleteRefs['services']])?></p>
<button class="danger" type="button" disabled><?=t('cust.delete_btn')?></button>
<?php endif;?>
</div></details></section>
<section class="section panel"><div class="sectionhead"><div><h2><?=t('cust.cars_title')?></h2><div class="tiny"><?=t('cust.cars_count',['n'=>count($customerCars)])?></div></div></div><?php if(!$customerCars):?><div class="empty"><?=t('cust.no_cars')?></div><?php else:?><div class="cars"><?php foreach($customerCars as $cc):?><a class="carcard" href="?car=<?=(int)$cc['id']?>"><div class="eyebrow"><?=h($cc['reg_plate']?:t('cust.car_fallback'))?></div><h3><?=h(carName($cc))?></h3><div class="statrow"><span><?=t('cust.odometer')?></span><strong><?=h(km((int)$cc['current_km']))?></strong></div><div class="statrow"><span><?=t('cust.services')?></span><strong><?=(int)$cc['service_count']?></strong></div><div class="statrow"><span><?=t('cust.last')?></span><strong><?=h(fiDate($cc['last_service_date']))?></strong></div></a><?php endforeach;?></div><?php endif;?></section>
<section class="section panel"><details class="clean"><summary><?=t('cust.history_summary')?></summary><div class="inside"><?php if(!$customerHistoryCars):?><div class="empty"><?=t('cust.no_history')?></div><?php else:?><div class="tablewrap"><table><thead><tr><th><?=t('cust.col_car')?></th><th><?=t('cust.col_from')?></th><th><?=t('cust.col_to')?></th><th><?=t('cust.col_name_snapshot')?></th></tr></thead><tbody><?php foreach($customerHistoryCars as $ch):?><tr><td><a href="?car=<?=(int)$ch['car_id']?>"><strong><?=h($ch['reg_plate']?:$ch['nickname'])?></strong> · <?=h(trim($ch['make'].' '.$ch['model']))?></a></td><td><?=h($ch['start_date']?fiDate($ch['start_date']):t('cust.unknown'))?></td><td><?=h($ch['end_date']?fiDate($ch['end_date']):t('cust.current'))?></td><td><?=h($ch['customer_name_snapshot'])?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></div></details></section>
<section class="section panel"><details class="clean" open><summary><?=t('cust.services_summary')?></summary><div class="inside"><div class="tiny" style="margin-bottom:10px"><?=t('cust.services_note')?></div><?php if(!$customerServices):?><div class="empty"><?=t('cust.no_services')?></div><?php else:foreach($customerServices as $cs):?><div class="kv"><span><a href="?car=<?=(int)$cs['car_id']?>&edit_service=<?=(int)$cs['id']?>#huolto"><strong><?=h($cs['reg_plate']?:$cs['nickname'])?></strong> · <?=h(fiDate($cs['service_date']))?></a></span><span><?=h($cs['title'])?> · <?=h(recordedKm((int)$cs['odometer']))?></span></div><?php endforeach;endif;?></div></details></section>
<?php else: ?>
<section class="hero panel"><div><div class="eyebrow"><?=t('cust.list_eyebrow')?></div><h1><?=t('cust.list_title')?></h1><div class="sub"><?=t('cust.list_intro')?></div></div><span class="badge"><?=t('cust.count',['n'=>count($customerList)])?></span></section>
<section class="section panel"><div class="sectionhead"><div><h2><?=t('cust.list_title')?></h2><div class="tiny"><?=t('cust.archive_note')?></div></div><input id="customerSearch" style="max-width:320px" placeholder="<?=t('cust.search_placeholder')?>"></div><div class="cars" id="customerCards"><?php foreach($customerList as $cu):$search=strtolower(implode(' ',[$cu['customer_number'],$cu['name'],$cu['contact_name'],$cu['phone'],$cu['email'],$cu['business_id']]));?><a class="carcard customer-card" href="?view=customers&customer=<?=(int)$cu['id']?>" data-search="<?=h($search)?>"><div class="eyebrow"><?=h(($cu['customer_number']?:('#'.$cu['id'])).' · '.customerTypeLabel((string)$cu['customer_type']))?></div><h3><?=h($cu['name'])?></h3><div class="statrow"><span><?=t('cust.cars')?></span><strong><?=(int)$cu['current_car_count']?></strong></div><?php if($cu['phone']):?><div class="statrow"><span><?=t('cust.phone')?></span><strong><?=h($cu['phone'])?></strong></div><?php endif;?><div class="statrow"><span><?=t('cust.status')?></span><strong><?=(int)$cu['active']===1?t('cust.active'):t('cust.archived')?></strong></div></a><?php endforeach;?></div></section>
<section class="section panel"><details class="clean" open><summary><?=t('cust.add')?></summary><div class="inside"><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="add_customer"><div class="grid grid4"><div><label><?=t('cust.number')?></label><input name="customer_number" value="<?=h(nextCustomerNumber($db))?>"></div><div><label><?=t('cust.type')?></label><select name="customer_type"><option value="private"><?=t('cust.type_private')?></option><option value="company"><?=t('cust.type_company')?></option></select></div><div><label><?=t('cust.name')?></label><input name="customer_name" required></div><div><label><?=t('cust.contact')?></label><input name="contact_name"></div><div><label><?=t('cust.phone')?></label><input name="phone"></div><div><label><?=t('cust.email')?></label><input name="email"></div><div><label><?=t('cust.street')?></label><input name="address"></div><div><label><?=t('cust.postal_code')?></label><input name="postal_code"></div><div><label><?=t('cust.city')?></label><input name="city"></div><div><label><?=t('cust.business_id')?></label><input name="business_id"></div><div><label style="margin-top:28px"><input type="checkbox" name="customer_active" value="1" checked> <?=t('cust.active')?></label></div><div><label><?=t('cust.notes')?></label><textarea name="customer_notes"></textarea></div></div><div class="form-actions"><button class="btn"><?=t('cust.add')?></button></div></form></div></details></section>
<?php endif; ?>
