<?php
declare(strict_types=1);
 ?>
<?php if($customer): ?>
<section class="hero panel"><div><div class="eyebrow">Asiakas <?=h($customer['customer_number']?:('#'.$customerId))?></div><h1><?=h($customer['name'])?></h1><div class="sub"><?=h(customerTypeLabel((string)$customer['customer_type']))?><?=trim((string)$customer['phone'])!==''?' · '.h($customer['phone']):''?><?=trim((string)$customer['email'])!==''?' · '.h($customer['email']):''?></div></div><div class="form-actions"><a class="btn2" href="?view=customers">← Asiakkaat</a></div></section>
<section class="section panel"><div class="sectionhead"><div><h2>Asiakastiedot</h2><div class="tiny">Asiakkaan muokkaaminen ei muuta vanhojen huoltojen tai laskujen snapshot-tietoja.</div></div><span class="badge"><?=(int)$customer['active']===1?'Käytössä':'Arkistoitu'?></span></div><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="update_customer"><?php editField($db,'customer',$customerId);?><input type="hidden" name="customer_id" value="<?=$customerId?>"><div class="grid grid4"><div><label>Asiakasnumero</label><input name="customer_number" value="<?=h($customer['customer_number'])?>"></div><div><label>Tyyppi</label><select name="customer_type"><option value="private" <?=$customer['customer_type']==='private'?'selected':''?>>Yksityinen</option><option value="company" <?=$customer['customer_type']==='company'?'selected':''?>>Yritys</option></select></div><div><label>Nimi / yritys</label><input name="customer_name" value="<?=h($customer['name'])?>" required></div><div><label>Yhteyshenkilö</label><input name="contact_name" value="<?=h($customer['contact_name'])?>"></div><div><label>Puhelin</label><input name="phone" value="<?=h($customer['phone'])?>"></div><div><label>Sähköposti</label><input name="email" value="<?=h($customer['email'])?>"></div><div><label>Katuosoite</label><input name="address" value="<?=h($customer['address'])?>"></div><div><label>Postinumero</label><input name="postal_code" value="<?=h($customer['postal_code'])?>"></div><div><label>Postitoimipaikka</label><input name="city" value="<?=h($customer['city'])?>"></div><div><label>Y-tunnus</label><input name="business_id" value="<?=h($customer['business_id'])?>"></div><div><label style="margin-top:28px"><input type="checkbox" name="customer_active" value="1" <?=(int)$customer['active']===1?'checked':''?>> Käytössä</label></div><div><label>Muistiinpanot</label><textarea name="customer_notes"><?=h($customer['notes'])?></textarea></div></div><div class="form-actions"><button class="btn">Tallenna asiakas</button></div></form></section>
<section class="section panel dangerzone"><details class="clean"><summary>🗑 Poista asiakas pysyvästi</summary><div class="inside">
<div class="flash warn">Pysyvä poisto onnistuu vain asiakkaalle, jota ei ole liitetty autoon eikä käytetty omistushistoriassa tai huoltojen asiakastiedoissa. Käytössä oleva asiakas kannattaa arkistoida.</div>
<?php if(!canAction('delete_customer')):?>
<p class="tiny">Pysyvä asiakaspoisto on vain ylläpitäjän toiminto.</p>
<?php elseif(customerDeleteAllowed($customerDeleteRefs)):?>
<form method="post" onsubmit="return confirm('Poistetaanko asiakas pysyvästi? Toimintoa ei voi perua.');"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="delete_customer"><input type="hidden" name="customer_id" value="<?=$customerId?>"><input type="hidden" name="delete_confirm" value="1"><button class="danger" type="submit">Poista asiakas pysyvästi</button></form>
<p class="tiny">Tällä hetkellä asiakkaalla ei ole sidoksia autoihin, omistushistoriaan tai huoltoihin.</p>
<?php else:?>
<p class="tiny"><strong>Poisto estetty:</strong> asiakkaalla on <?=$customerDeleteRefs['cars']?> nykyistä autoa, <?=$customerDeleteRefs['history']?> omistushistorian riviä ja <?=$customerDeleteRefs['services']?> huoltoa.</p>
<button class="danger" type="button" disabled>Poista asiakas pysyvästi</button>
<?php endif;?>
</div></details></section>
<section class="section panel"><div class="sectionhead"><div><h2>🚗 Nykyiset autot</h2><div class="tiny"><?=count($customerCars)?> autoa on tällä hetkellä liitetty tähän asiakkaaseen.</div></div></div><?php if(!$customerCars):?><div class="empty">Ei nykyisiä autoja.</div><?php else:?><div class="cars"><?php foreach($customerCars as $cc):?><a class="carcard" href="?car=<?=(int)$cc['id']?>"><div class="eyebrow"><?=h($cc['reg_plate']?:'AUTO')?></div><h3><?=h(carName($cc))?></h3><div class="statrow"><span>Mittari</span><strong><?=h(km((int)$cc['current_km']))?></strong></div><div class="statrow"><span>Huoltoja</span><strong><?=(int)$cc['service_count']?></strong></div><div class="statrow"><span>Viimeisin</span><strong><?=h(fiDate($cc['last_service_date']))?></strong></div></a><?php endforeach;?></div><?php endif;?></section>
<section class="section panel"><details class="clean"><summary>🕘 Omistushistoria</summary><div class="inside"><?php if(!$customerHistoryCars):?><div class="empty">Omistushistoriaa ei ole vielä.</div><?php else:?><div class="tablewrap"><table><thead><tr><th>Auto</th><th>Alkaen</th><th>Päättyen</th><th>Nimi snapshot</th></tr></thead><tbody><?php foreach($customerHistoryCars as $ch):?><tr><td><a href="?car=<?=(int)$ch['car_id']?>"><strong><?=h($ch['reg_plate']?:$ch['nickname'])?></strong> · <?=h(trim($ch['make'].' '.$ch['model']))?></a></td><td><?=h($ch['start_date']?fiDate($ch['start_date']):'ei tiedossa')?></td><td><?=h($ch['end_date']?fiDate($ch['end_date']):'nykyinen')?></td><td><?=h($ch['customer_name_snapshot'])?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></div></details></section>
<section class="section panel"><details class="clean" open><summary>🔧 Huoltohistoria asiakkaan autoista</summary><div class="inside"><div class="tiny" style="margin-bottom:10px">Uusissa huolloissa asiakas tunnistetaan tapahtumahetken snapshotista. Vanhoista, ennen asiakasrekisteriä tehdyistä merkinnöistä näytetään myös asiakkaan nykyisten autojen historia.</div><?php if(!$customerServices):?><div class="empty">Huoltoja ei löytynyt.</div><?php else:foreach($customerServices as $cs):?><div class="kv"><span><a href="?car=<?=(int)$cs['car_id']?>&edit_service=<?=(int)$cs['id']?>#huolto"><strong><?=h($cs['reg_plate']?:$cs['nickname'])?></strong> · <?=h(fiDate($cs['service_date']))?></a></span><span><?=h($cs['title'])?> · <?=h(recordedKm((int)$cs['odometer']))?></span></div><?php endforeach;endif;?></div></details></section>
<?php else: ?>
<section class="hero panel"><div><div class="eyebrow">Asiakasrekisteri</div><h1>Asiakkaat</h1><div class="sub">Yksi asiakas voi omistaa useita autoja. Asiakkaan tiedot ylläpidetään yhdessä paikassa.</div></div><span class="badge"><?=count($customerList)?> asiakasta</span></section>
<section class="section panel"><div class="sectionhead"><div><h2>Asiakkaat</h2><div class="tiny">Arkistointi ei poista asiakasta eikä historiaa.</div></div><input id="customerSearch" style="max-width:320px" placeholder="Hae nimellä, numerolla, puhelimella, sähköpostilla..."></div><div class="cars" id="customerCards"><?php foreach($customerList as $cu):$search=strtolower(implode(' ',[$cu['customer_number'],$cu['name'],$cu['contact_name'],$cu['phone'],$cu['email'],$cu['business_id']]));?><a class="carcard customer-card" href="?view=customers&customer=<?=(int)$cu['id']?>" data-search="<?=h($search)?>"><div class="eyebrow"><?=h(($cu['customer_number']?:('#'.$cu['id'])).' · '.customerTypeLabel((string)$cu['customer_type']))?></div><h3><?=h($cu['name'])?></h3><div class="statrow"><span>Autot</span><strong><?=(int)$cu['current_car_count']?></strong></div><?php if($cu['phone']):?><div class="statrow"><span>Puhelin</span><strong><?=h($cu['phone'])?></strong></div><?php endif;?><div class="statrow"><span>Tila</span><strong><?=(int)$cu['active']===1?'Käytössä':'Arkistoitu'?></strong></div></a><?php endforeach;?></div></section>
<section class="section panel"><details class="clean" open><summary>＋ Lisää asiakas</summary><div class="inside"><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="add_customer"><div class="grid grid4"><div><label>Asiakasnumero</label><input name="customer_number" value="<?=h(nextCustomerNumber($db))?>"></div><div><label>Tyyppi</label><select name="customer_type"><option value="private">Yksityinen</option><option value="company">Yritys</option></select></div><div><label>Nimi / yritys</label><input name="customer_name" required></div><div><label>Yhteyshenkilö</label><input name="contact_name"></div><div><label>Puhelin</label><input name="phone"></div><div><label>Sähköposti</label><input name="email"></div><div><label>Katuosoite</label><input name="address"></div><div><label>Postinumero</label><input name="postal_code"></div><div><label>Postitoimipaikka</label><input name="city"></div><div><label>Y-tunnus</label><input name="business_id"></div><div><label style="margin-top:28px"><input type="checkbox" name="customer_active" value="1" checked> Käytössä</label></div><div><label>Muistiinpanot</label><textarea name="customer_notes"></textarea></div></div><div class="form-actions"><button class="btn">＋ Lisää asiakas</button></div></form></div></details></section>
<?php endif; ?>
