<?php
declare(strict_types=1);
$inventoryEditable=canAction('bulk_update_inventory');
$canMove=canAction('adjust_part_stock');$canAddPart=canAction('add_part');
$inventoryCars=[];foreach($cars as $ic){$iid=(int)$ic['id'];$inventoryCars[$iid]=trim((string)($ic['reg_plate']?:$ic['nickname']).' · '.trim((string)$ic['make'].' '.(string)$ic['model']));}asort($inventoryCars,SORT_NATURAL|SORT_FLAG_CASE);
$invHasPrice=(bool)array_filter($inventoryParts,fn($p)=>$p['purchase_price']!==null);
?>
<section class="hero panel"><div><div class="eyebrow">Osalaatikko</div><h1>📦 Varaosavarasto</h1><div class="sub">Saldot, hyllypaikat ja varoitusrajat. Kirjaa tulleet ja otetut osat rivin +/− -painikkeilla.</div></div><div class="form-actions"><span class="badge" id="inventoryCountBadge"><?=count($inventoryParts)?> nimikettä</span><button type="button" class="badge badge-btn" id="inventoryLowBadge" title="Näytä vain vähissä olevat">⚠️ <?=$inventoryLow?> varoitusrajalla</button><span class="badge">Arvo <span id="inventoryValueBadge"><?=$invHasPrice?h(money($inventoryValue)):'–'?></span></span><?php if($canAddPart&&$inventoryCars):?><button type="button" class="btn" id="addPartOpen">＋ Lisää varaosa</button><?php endif;?></div></section>
<section class="section panel inventory-panel"><div class="sectionhead"><div><h2>Varastosaldot</h2><div class="tiny"><?= $inventoryEditable?'Voit korjata useita rivejä ja tallentaa ne yhdellä kertaa. Saldon muutos kirjautuu automaattisesti varastohistoriaan saldokorjauksena.':'Katseluoikeus: nimikkeet, saldot ja hinnat näkyvät, mutta tietoja ei voi muuttaa.' ?></div></div></div>
<?php if(!$inventoryParts):?><div class="empty">Varaosamuistiossa ei ole vielä nimikkeitä.</div><?php else:
?>
<div class="inventory-tools"><div><label>Haku</label><input id="inventorySearch" placeholder="Osa, numero, auto, omistaja, hyllypaikka..."></div><div><label>Auto</label><select id="inventoryCarFilter"><option value="">Kaikki autot</option><?php foreach($inventoryCars as $iid=>$iname):?><option value="<?=$iid?>"><?=h($iname)?></option><?php endforeach;?></select></div><div><label>Lajittelu</label><select id="inventorySortSelect"><option value="car:asc">Sopivuus A–Ö</option><option value="part:asc">Varaosa A–Ö</option><option value="stock:asc">Saldo pienin ensin</option><option value="stock:desc">Saldo suurin ensin</option><option value="price:asc">Hinta pienin ensin</option><option value="price:desc">Hinta suurin ensin</option><option value="value:desc">Saldoarvo suurin ensin</option><option value="reorder:asc">Varoitusraja pienin ensin</option><option value="reorder:desc">Varoitusraja suurin ensin</option><option value="shelf:asc">Hyllypaikka A–Ö</option></select></div><label class="inventory-low-filter"><input type="checkbox" id="inventoryLowOnly"> <span><strong>⚠️ Vain vähissä</strong><small>Saldo on varoitusrajalla tai sen alla</small></span></label><div class="inventory-print-group"><a class="btn2 inventory-print" id="inventoryPrintLink" target="_blank" href="?print=inventory" title="Tulostaa näkyvät rivit tyhjällä Laskettu-sarakkeella, jonka voi täyttää käsin hyllyllä">🖨 Inventointilista</a><a class="btn2 inventory-print" id="inventoryPrintInfoLink" target="_blank" href="?print=inventory&amp;mode=info" title="Tulostaa näkyvät rivit hintoineen, saldoarvoineen, tiloineen ja muistiinpanoineen">🖨 Varaston tiedot</a><a class="btn2 inventory-print" id="inventoryExcelLink" href="?export=inventory_xlsx">📊 Excel</a></div></div>
<?php if($inventoryEditable):?><form method="post" id="inventoryBulkForm"><?php else:?><div id="inventoryBulkForm" data-readonly="1"><?php endif;?><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="bulk_update_inventory">
<div class="inventory-table-wrap"><table class="inventory-table" id="inventoryTable"><thead><tr><th><button type="button" class="inventory-sort" data-sort="car">Sopii autoihin</button></th><th><button type="button" class="inventory-sort" data-sort="part">Varaosa</button></th><th><button type="button" class="inventory-sort" data-sort="shelf">Hylly</button></th><th><button type="button" class="inventory-sort" data-sort="stock">Saldo</button></th><th>Yksikkö</th><th><button type="button" class="inventory-sort" data-sort="reorder">Varoitusraja</button></th><th><button type="button" class="inventory-sort" data-sort="price"><?=h(purchasePriceLabel($app))?></button></th><th><button type="button" class="inventory-sort" data-sort="value">Saldoarvo</button></th><th></th></tr></thead><tbody id="inventoryTableBody">
<?php foreach($inventoryParts as $ip):$low=$ip['reorder_level']!==null&&(float)$ip['stock_qty']<=(float)$ip['reorder_level'];$pid=(int)$ip['id'];$carLabel=trim((string)($ip['reg_plate']?:$ip['nickname']));$compatLabel=(string)($ip['compat_labels']??$carLabel);$compatIds=array_filter(explode(',',(string)($ip['compat_car_ids']??'')));$compatCount=count($compatIds);$compatShort=$compatCount>2?implode(', ',array_map(fn($x)=>trim(explode(' · ',$x)[0]),explode(' / ',$compatLabel))):'';$openCar=(int)($ip['open_car_id']??$ip['car_id']);$cp=[];$cm=[];foreach(explode(' / ',$compatLabel) as $cl){$pp=explode(' · ',$cl,2);$cp[]=trim($pp[0]);if(isset($pp[1])&&trim($pp[1])!=='')$cm[]=trim($pp[1]);}$compatPlates=implode(' / ',array_filter($cp));$compatModels=implode(' / ',$cm);$partMeta=trim(implode(' · ',array_filter([(string)$ip['brand'],(string)$ip['supplier_sku'],(string)$ip['oem_number']!==''?'OEM '.(string)$ip['oem_number']:''])));$search=strtolower(implode(' ',[$ip['part_name'],$ip['brand'],$ip['supplier_sku'],$ip['oem_number'],$ip['shelf_location'],$ip['compat_search']??'']));?>
<tr class="inventory-row<?=$low?' inventory-low':''?>" data-search="<?=h($search)?>" data-car-ids=",<?=h((string)($ip['compat_car_ids']??$ip['car_id']))?>," data-car-name="<?=h(strtolower($compatLabel))?>" data-part-name="<?=h(strtolower((string)$ip['part_name'].' '.$partMeta))?>">
<td data-label="Sopii autoihin"><a href="?car=<?=$openCar?>#varaosat" <?=$compatCount>2?'title="'.h($compatLabel).'"':''?>><strong><?=$compatCount>2?$compatCount.' autoa':h($compatPlates?:'Auto #'.(int)$ip['car_id'])?></strong><?php if($compatCount>2):?><span class="inventory-cell-sub"><?=h($compatShort)?></span><?php elseif($compatModels!==''):?><span class="inventory-cell-sub"><?=h($compatModels)?></span><?php endif;?><?php if($compatCount>1):?><span class="inventory-cell-sub">Yhteinen varaosa · yksi saldo</span><?php endif;?></a></td>
<td data-label="Varaosa"><?php if($inventoryEditable):?><input type="hidden" name="inventory_baseline[<?=$pid?>]" value="<?=h(editToken($db,'inventory',$pid,inventoryEditValues($ip)))?>"><?php endif;?><strong><?=h($ip['part_name'])?></strong><?php if($partMeta!==''):?><span class="inventory-cell-sub"><?=h($partMeta)?></span><?php endif;?></td>
<td data-label="Hylly"><input <?= $inventoryEditable?'':'readonly aria-readonly="true"' ?> class="inventory-edit inventory-shelf" name="inventory_shelf_location[<?=$pid?>]" value="<?=h($ip['shelf_location']??'')?>" placeholder="–"></td>
<td data-label="Saldo"><div class="inventory-number-wrap"><input <?= $inventoryEditable?'':'readonly aria-readonly="true"' ?> class="inventory-edit inventory-stock" name="inventory_stock_qty[<?=$pid?>]" inputmode="decimal" type="number" min="0" step="0.01" value="<?=h((string)(float)$ip['stock_qty'])?>" required><?php if($canMove):?><button type="button" class="btn2 stock-move-btn" data-dir="out" data-part="<?=$pid?>" data-car="<?=$openCar?>" data-name="<?=h($ip['part_name'])?>" data-unit="<?=h($ip['stock_unit']?:'kpl')?>" data-stock="<?=h((string)(float)$ip['stock_qty'])?>" title="Otettu varastosta" aria-label="Otettu varastosta">−</button><button type="button" class="btn2 stock-move-btn" data-dir="in" data-part="<?=$pid?>" data-car="<?=$openCar?>" data-name="<?=h($ip['part_name'])?>" data-unit="<?=h($ip['stock_unit']?:'kpl')?>" data-stock="<?=h((string)(float)$ip['stock_qty'])?>" title="Lisätty varastoon" aria-label="Lisätty varastoon">＋</button><?php endif;?><span class="inventory-unit-label"><?=h($ip['stock_unit']?:'kpl')?></span><span class="inventory-low-mark" title="Saldo on varoitusrajalla tai sen alla">⚠️ Vähissä</span></div></td>
<td class="inv-extra" data-label="Yksikkö"><input <?= $inventoryEditable?'':'readonly aria-readonly="true"' ?> class="inventory-edit inventory-unit" name="inventory_stock_unit[<?=$pid?>]" value="<?=h($ip['stock_unit']?:'kpl')?>" maxlength="20" required></td>
<td class="inv-extra" data-label="Varoitusraja"><input <?= $inventoryEditable?'':'readonly aria-readonly="true"' ?> class="inventory-edit inventory-reorder" name="inventory_reorder_level[<?=$pid?>]" inputmode="decimal" type="number" min="0" step="0.01" value="<?=$ip['reorder_level']!==null?h((string)(float)$ip['reorder_level']):''?>" placeholder="–"></td>
<td class="inv-extra" data-label="<?=h(purchasePriceLabel($app))?>"><div class="inventory-price-input"><input <?= $inventoryEditable?'':'readonly aria-readonly="true"' ?> class="inventory-edit inventory-price" name="inventory_purchase_price[<?=$pid?>]" inputmode="decimal" type="number" min="0" step="0.01" value="<?=$ip['purchase_price']!==null?h((string)(float)$ip['purchase_price']):''?>" placeholder="–"><span>€</span></div></td>
<td class="inv-extra" data-label="Saldoarvo"><strong class="inventory-row-value"><?=$ip['purchase_price']!==null?h(money((float)$ip['stock_qty']*(float)$ip['purchase_price'])):'–'?></strong></td>
<td data-label="" class="inventory-actions"><button type="button" class="btn2 inventory-more" aria-expanded="false">Lisätiedot ▾</button><a class="btn2 inventory-open" href="?car=<?=$openCar?>#varaosat" title="Avaa auton varaosat">Auton osat ›</a></td></tr>
<?php endforeach;?></tbody></table></div>
<?php if($inventoryEditable):?><input type="hidden" name="inventory_complete" value="1"><?php endif;?><div class="inventory-savebar"><div><strong id="inventoryVisibleCount"><?=count($inventoryParts)?> riviä näkyvissä</strong><span class="tiny" id="inventoryDirtyText">Ei tallentamattomia muutoksia.</span></div><?php if($inventoryEditable):?><button class="btn" id="inventorySaveButton" type="submit">💾 Tallenna muutokset</button><?php endif;?></div><?php if($inventoryEditable):?></form><?php else:?></div><?php endif;?>
<?php endif;?></section>
<?php if($canMove):?>
<dialog id="stockMoveDialog" class="app-dialog"><form method="post" id="stockMoveForm"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="adjust_part_stock"><input type="hidden" name="return" value="inventory"><input type="hidden" name="part_id" id="smPart" value=""><input type="hidden" name="car_id" id="smCar" value="">
<h3 id="smTitle">Varastotapahtuma</h3><div class="tiny" id="smInfo"></div>
<div class="sm-dir"><label class="sm-choice"><input type="radio" name="stock_direction" value="in" id="smIn"> <span>＋ Lisätty varastoon</span></label><label class="sm-choice"><input type="radio" name="stock_direction" value="out" id="smOut"> <span>− Otettu varastosta</span></label></div>
<div class="grid grid2"><div><label>Määrä <span id="smUnit"></span></label><input name="stock_qty" id="smQty" inputmode="decimal" type="number" min="0.01" step="0.01" required></div><div><label>Syy / muistiinpano (valinnainen)</label><input name="stock_note" id="smNote" maxlength="200" placeholder="Esim. tilaus saapui, otettu huoltoon"></div></div>
<div class="tiny">Kirjataan heti varastohistoriaan. Saldotaulukon muut muutokset tallennetaan erikseen.</div>
<div class="form-actions" style="margin-top:14px"><button class="btn" type="submit">Kirjaa</button><button class="btn2" type="button" data-close-dialog>Peruuta</button></div></form></dialog>
<?php endif;?>
<?php if($canAddPart&&$inventoryCars):$addItems=allItems($db,true);?>
<dialog id="addPartDialog" class="app-dialog app-dialog-wide"><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="add_part"><input type="hidden" name="return" value="inventory">
<h3>Lisää varaosa varastoon</h3><div class="grid grid2"><div><label>Auto (ensisijainen)</label><select name="car_id" id="apCar" required><?php foreach($inventoryCars as $iid=>$iname):?><option value="<?=$iid?>"><?=h($iname?:'Auto #'.$iid)?></option><?php endforeach;?></select></div><div><label>Kohde</label><select name="part_item_key"><option value="">Muu varaosa</option><?php foreach($addItems as $ai):?><option value="<?=h($ai['item_key'])?>"><?=h($ai['label'])?></option><?php endforeach;?></select></div><div><label>Nimi</label><input name="part_name" required></div><div><label>Merkki</label><input name="part_brand"></div><div><label>Varaosanumero</label><input name="part_supplier_sku"></div><div><label>OEM</label><input name="part_oem_number"></div></div>
<div style="margin-top:10px"><label>Sopii myös näihin autoihin</label><div class="compat-grid"><?php foreach($inventoryCars as $iid=>$iname):?><label class="compat-choice" data-car="<?=$iid?>"><input type="checkbox" name="part_compatible_cars[]" value="<?=$iid?>"> <span><?=h($iname?:'Auto #'.$iid)?></span></label><?php endforeach;?></div><div class="tiny">Valitse autot, joihin sama fyysinen varaosa sopii. Ensisijainen auto lisätään aina.</div></div>
<div class="grid grid4" style="margin-top:10px"><div><label>Alkusaldo</label><input name="part_stock_qty" inputmode="decimal" value="0"></div><div><label>Yksikkö</label><select name="part_stock_unit"><option>kpl</option><option>L</option><option>sarja</option><option>pkt</option></select></div><div><label>Hyllypaikka</label><input name="part_shelf_location"></div><div><label>Varoitusraja</label><input name="part_reorder_level" inputmode="decimal"></div><div><label><?=h(purchasePriceLabel($app,'Hankintahinta / yksikkö'))?></label><input name="part_purchase_price" inputmode="decimal"></div><div><label>Muistiinpano</label><input name="part_notes"></div><div style="grid-column:span 2"><label>Linkki</label><input type="url" name="part_url"></div></div>
<div class="form-actions" style="margin-top:14px"><button class="btn" type="submit">Lisää varaosa</button><button class="btn2" type="button" data-close-dialog>Peruuta</button></div></form></dialog>
<?php endif;?>
<?php
$stockRequested=filter_var($_GET['stock_page']??1,FILTER_VALIDATE_INT);$stockPartFilter=filter_var($_GET['stock_part']??0,FILTER_VALIDATE_INT);
$stockPartFilter=$stockPartFilter===false?0:max(0,$stockPartFilter);$stockTypeFilter=is_string($_GET['stock_type']??null)?trim($_GET['stock_type']):'';
$stockEvents=inventoryHistoryPage($db,$stockRequested===false?1:$stockRequested,$stockPartFilter,$stockTypeFilter);
$stockTypes=$db->query('SELECT DISTINCT event_type FROM inventory_transactions ORDER BY event_type')->fetchAll(PDO::FETCH_COLUMN);
$stockHistoryLink=static fn(int $page):string=>'?'.http_build_query(['view'=>'inventory','stock_page'=>$page,'stock_part'=>$stockPartFilter,'stock_type'=>$stockTypeFilter]).'#varastotapahtumat';
?>
<section class="section panel" id="stockHistoryPanel"><details class="clean" id="varastotapahtumat" <?=isset($_GET['stock_page'])?'open':''?>><summary>🕘 Varastotapahtumat · <?=$stockEvents['all_total']?></summary><div class="inside">
<p class="tiny">Lisäykset, otot, saldokorjaukset ja huoltojen varastokäyttö. Uusimmat ensin, enintään 50 tapahtumaa sivulla. Rajaukset koskevat tätä tapahtumaluetteloa; saldotaulukon rajaukset ovat erilliset.</p>
<?php if(!empty($app['inventory_history_cleared_at'])):?><p class="tiny stock-history-last-clear">Viimeisin historian tyhjennys <?=h(date('d.m.Y H:i',strtotime($app['inventory_history_cleared_at'])))?> · <?=h($app['inventory_history_cleared_by']??'')?> · <?=(int)($app['inventory_history_cleared_count']??0)?> tapahtumaa. Saldot säilytettiin.</p><?php endif;?>
<form method="get" class="stock-history-filters"><input type="hidden" name="view" value="inventory"><input type="hidden" name="stock_page" value="1"><div class="grid grid2"><div><label>Nimike</label><select name="stock_part"><option value="0">Kaikki nimikkeet</option><?php foreach($inventoryParts as $sp):?><option value="<?=(int)$sp['id']?>" <?=$stockPartFilter===(int)$sp['id']?'selected':''?>><?=h(trim($sp['part_name'].' · '.$sp['brand'].' '.$sp['supplier_sku']))?></option><?php endforeach;?></select></div><div><label>Tapahtumatyyppi</label><select name="stock_type"><option value="">Kaikki tapahtumat</option><?php foreach($stockTypes as $type):?><option value="<?=h($type)?>" <?=$stockTypeFilter===$type?'selected':''?>><?=h(inventoryEventLabel($type))?></option><?php endforeach;?></select></div></div><div class="form-actions"><button class="btn2">Rajaa tapahtumat</button><a class="btn2" href="?view=inventory&stock_page=1#varastotapahtumat">Poista rajaus</a></div></form>
<p class="tiny stock-history-count"><?=$stockEvents['total']?'Näytetään '.($stockEvents['offset']+1).'–'.($stockEvents['offset']+count($stockEvents['rows'])).' / '.$stockEvents['total'].' tapahtumaa.':'Ei tapahtumia tässä rajauksessa.'?></p>
<?php if($stockEvents['rows']):?><table class="stock-events-table"><thead><tr><th>Päivä / aika</th><th>Varaosa</th><th>Tapahtuma</th><th>Muutos</th><th>Saldo jälkeen</th><th>Selite</th></tr></thead><tbody>
<?php foreach($stockEvents['rows'] as $stx):?><tr class="stock-event-row"><td data-label="Päivä / aika"><?=h(date('d.m.Y H:i',strtotime($stx['created_at'])))?></td><td data-label="Varaosa"><a href="?car=<?=(int)$stx['car_id']?>#varaosat"><strong><?=h($stx['part_name'])?></strong></a><div class="tiny"><?=h(trim($stx['brand'].' '.$stx['supplier_sku']))?></div></td><td data-label="Tapahtuma"><?=h(inventoryEventLabel($stx['event_type']))?></td><td data-label="Muutos"><strong><?=((float)$stx['quantity_change']>0?'+':'')?><?=h(dec((float)$stx['quantity_change'],2).' '.($stx['stock_unit']?:'kpl'))?></strong></td><td data-label="Saldo jälkeen"><?=h(dec((float)$stx['stock_after'],2).' '.($stx['stock_unit']?:'kpl'))?></td><td data-label="Selite" class="stock-events-note"><?=h($stx['note'])?></td></tr><?php endforeach;?></tbody></table><?php endif;?>
<?php if($stockEvents['pages']>1):?><nav class="form-actions" aria-label="Varastotapahtumien sivut"><?php if($stockEvents['page']>1):?><a class="btn2" href="<?=h($stockHistoryLink(1))?>">Uusimmat</a><a class="btn2" href="<?=h($stockHistoryLink($stockEvents['page']-1))?>">← Edellinen</a><?php endif;?><span class="tiny">Sivu <?=$stockEvents['page']?> / <?=$stockEvents['pages']?></span><?php if($stockEvents['page']<$stockEvents['pages']):?><a class="btn2" href="<?=h($stockHistoryLink($stockEvents['page']+1))?>">Seuraava →</a><a class="btn2" href="<?=h($stockHistoryLink($stockEvents['pages']))?>">Vanhimmat</a><?php endif;?></nav><?php endif;?>
<?php if(canAction('clear_inventory_history')):?><details class="clean" style="margin-top:18px"><summary>Tyhjennä varastotapahtumien historia</summary><div class="inside"><p class="tiny">Tallenna ensin inventaarion korjatut saldot. Voit ottaa vanhan historian Excel-vientiin tai täyteen varmuuskopioon ennen tyhjennystä. Poisto koskee kaikkia nimikkeitä ja kaikkia tapahtumasivuja, myös tämän rajauksen ulkopuolella. Saldot, varaosat, huollot ja huoltoihin liitetty varastokäyttö säilyvät.</p>
<form method="post" class="clear-stock-history-form"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="clear_inventory_history"><input type="hidden" name="stock_history_up_to" value="<?=$stockEvents['last_id']?>"><label><input type="checkbox" name="stock_history_confirm" value="1" required> Ymmärrän, että kaikkien nimikkeiden tapahtumahistoria poistetaan pysyvästi</label><div class="form-actions"><button class="danger">Tyhjennä varastotapahtumat</button></div><p class="tiny">Lomakkeen avaamisen jälkeen syntyneet uudet tapahtumat säilyvät. Tyhjennyksen ajankohta ja tekijä jäävät näkyviin. Vapautunut tila voidaan käyttää tietokannassa uudelleen; tiedoston koko ei välttämättä pienene heti.</p></form></div></details><?php endif;?>
</div></details></section>
<?php if($inventoryParts):?><?php endif;?>
