<?php
declare(strict_types=1);
$inventoryEditable=canAction('bulk_update_inventory');
$canMove=canAction('adjust_part_stock');$canAddPart=canAction('add_part');
$inventoryCars=[];foreach($cars as $ic){$iid=(int)$ic['id'];$inventoryCars[$iid]=trim((string)($ic['reg_plate']?:$ic['nickname']).' · '.trim((string)$ic['make'].' '.(string)$ic['model']));}asort($inventoryCars,SORT_NATURAL|SORT_FLAG_CASE);
$invHasPrice=(bool)array_filter($inventoryParts,fn($p)=>$p['purchase_price']!==null);
?>
<section class="hero panel"><div><div class="eyebrow"><?=t('inv.eyebrow')?></div><h1><?=t('inv.title')?></h1><div class="sub"><?=t('inv.subtitle')?></div></div><div class="form-actions"><span class="badge" id="inventoryCountBadge"><?=t('inv.items_count',['n'=>count($inventoryParts)])?></span><button type="button" class="badge badge-btn" id="inventoryLowBadge" title="<?=t('inv.low_badge_title')?>"><?=t('inv.low_badge',['n'=>$inventoryLow])?></button><span class="badge"><?=t('inv.value')?> <span id="inventoryValueBadge"><?=$invHasPrice?h(money($inventoryValue)):'–'?></span></span><?php if($canAddPart&&$inventoryCars):?><button type="button" class="btn" id="addPartOpen"><?=t('inv.add_part_open')?></button><?php endif;?></div></section>
<section class="section panel inventory-panel"><div class="sectionhead"><div><h2><?=t('inv.balances_heading')?></h2><div class="tiny"><?= $inventoryEditable?t('inv.balances_help_edit'):t('inv.balances_help_view') ?></div></div></div>
<?php if(!$inventoryParts):?><div class="empty"><?=t('inv.empty')?></div><?php else:
?>
<div class="inventory-tools"><div><label><?=t('inv.search_label')?></label><input id="inventorySearch" placeholder="<?=t('inv.search_placeholder')?>"></div><div><label><?=t('inv.car_label')?></label><select id="inventoryCarFilter"><option value=""><?=t('inv.all_cars')?></option><?php foreach($inventoryCars as $iid=>$iname):?><option value="<?=$iid?>"><?=h($iname)?></option><?php endforeach;?></select></div><div><label><?=t('inv.sort_label')?></label><select id="inventorySortSelect"><option value="car:asc"><?=t('inv.sort_car_asc')?></option><option value="part:asc"><?=t('inv.sort_part_asc')?></option><option value="stock:asc"><?=t('inv.sort_stock_asc')?></option><option value="stock:desc"><?=t('inv.sort_stock_desc')?></option><option value="price:asc"><?=t('inv.sort_price_asc')?></option><option value="price:desc"><?=t('inv.sort_price_desc')?></option><option value="value:desc"><?=t('inv.sort_value_desc')?></option><option value="reorder:asc"><?=t('inv.sort_reorder_asc')?></option><option value="reorder:desc"><?=t('inv.sort_reorder_desc')?></option><option value="shelf:asc"><?=t('inv.sort_shelf_asc')?></option></select></div><label class="inventory-low-filter"><input type="checkbox" id="inventoryLowOnly"> <span><strong><?=t('inv.low_only')?></strong><small><?=t('inv.low_note')?></small></span></label><div class="inventory-print-group"><a class="btn2 inventory-print" id="inventoryPrintLink" target="_blank" href="?print=inventory" title="<?=t('inv.print_count_title')?>"><?=t('inv.print_count')?></a><a class="btn2 inventory-print" id="inventoryPrintInfoLink" target="_blank" href="?print=inventory&amp;mode=info" title="<?=t('inv.print_info_title')?>"><?=t('inv.print_info')?></a><a class="btn2 inventory-print" id="inventoryExcelLink" href="?export=inventory_xlsx"><?=t('inv.excel')?></a></div></div>
<?php if($inventoryEditable):?><form method="post" id="inventoryBulkForm"><?php else:?><div id="inventoryBulkForm" data-readonly="1"><?php endif;?><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="bulk_update_inventory">
<div class="inventory-table-wrap"><table class="inventory-table" id="inventoryTable"><thead><tr><th><button type="button" class="inventory-sort" data-sort="car"><?=t('inv.col_cars')?></button></th><th><button type="button" class="inventory-sort" data-sort="part"><?=t('inv.col_part')?></button></th><th><button type="button" class="inventory-sort" data-sort="shelf"><?=t('inv.col_shelf')?></button></th><th><button type="button" class="inventory-sort" data-sort="stock"><?=t('inv.col_stock')?></button></th><th><?=t('inv.col_unit')?></th><th><button type="button" class="inventory-sort" data-sort="reorder"><?=t('inv.col_reorder')?></button></th><th><button type="button" class="inventory-sort" data-sort="price"><?=h(purchasePriceLabel($app))?></button></th><th><button type="button" class="inventory-sort" data-sort="value"><?=t('inv.col_value')?></button></th><th></th></tr></thead><tbody id="inventoryTableBody">
<?php foreach($inventoryParts as $ip):$low=$ip['reorder_level']!==null&&(float)$ip['stock_qty']<=(float)$ip['reorder_level'];$pid=(int)$ip['id'];$carLabel=trim((string)($ip['reg_plate']?:$ip['nickname']));$compatLabel=(string)($ip['compat_labels']??$carLabel);$compatIds=array_filter(explode(',',(string)($ip['compat_car_ids']??'')));$compatCount=count($compatIds);$compatShort=$compatCount>2?implode(', ',array_map(fn($x)=>trim(explode(' · ',$x)[0]),explode(' / ',$compatLabel))):'';$openCar=(int)($ip['open_car_id']??$ip['car_id']);$cp=[];$cm=[];foreach(explode(' / ',$compatLabel) as $cl){$pp=explode(' · ',$cl,2);$cp[]=trim($pp[0]);if(isset($pp[1])&&trim($pp[1])!=='')$cm[]=trim($pp[1]);}$compatPlates=implode(' / ',array_filter($cp));$compatModels=implode(' / ',$cm);$partMeta=trim(implode(' · ',array_filter([(string)$ip['brand'],(string)$ip['supplier_sku'],(string)$ip['oem_number']!==''?t('inv.oem_meta',['oem'=>(string)$ip['oem_number']]):''])));$search=strtolower(implode(' ',[$ip['part_name'],$ip['brand'],$ip['supplier_sku'],$ip['oem_number'],$ip['shelf_location'],$ip['compat_search']??'']));?>
<tr class="inventory-row<?=$low?' inventory-low':''?>" data-search="<?=h($search)?>" data-car-ids=",<?=h((string)($ip['compat_car_ids']??$ip['car_id']))?>," data-car-name="<?=h(strtolower($compatLabel))?>" data-part-name="<?=h(strtolower((string)$ip['part_name'].' '.$partMeta))?>">
<td data-label="<?=t('inv.col_cars')?>"><a href="?car=<?=$openCar?>#varaosat" <?=$compatCount>2?'title="'.h($compatLabel).'"':''?>><strong><?=$compatCount>2?t('inv.cars_count',['n'=>$compatCount]):h($compatPlates?:t('inv.car_number',['n'=>(int)$ip['car_id']]))?></strong><?php if($compatCount>2):?><span class="inventory-cell-sub"><?=h($compatShort)?></span><?php elseif($compatModels!==''):?><span class="inventory-cell-sub"><?=h($compatModels)?></span><?php endif;?><?php if($compatCount>1):?><span class="inventory-cell-sub"><?=t('inv.shared_part')?></span><?php endif;?></a></td>
<td data-label="<?=t('inv.col_part')?>"><?php if($inventoryEditable):?><input type="hidden" name="inventory_baseline[<?=$pid?>]" value="<?=h(editToken($db,'inventory',$pid,inventoryEditValues($ip)))?>"><?php endif;?><strong><?=h($ip['part_name'])?></strong><?php if($partMeta!==''):?><span class="inventory-cell-sub"><?=h($partMeta)?></span><?php endif;?></td>
<td data-label="<?=t('inv.col_shelf')?>"><input <?= $inventoryEditable?'':'readonly aria-readonly="true"' ?> class="inventory-edit inventory-shelf" name="inventory_shelf_location[<?=$pid?>]" value="<?=h($ip['shelf_location']??'')?>" placeholder="–"></td>
<td data-label="<?=t('inv.col_stock')?>"><div class="inventory-number-wrap"><input <?= $inventoryEditable?'':'readonly aria-readonly="true"' ?> class="inventory-edit inventory-stock" name="inventory_stock_qty[<?=$pid?>]" inputmode="decimal" type="number" min="0" step="0.01" value="<?=h((string)(float)$ip['stock_qty'])?>" required><?php if($canMove):?><button type="button" class="btn2 stock-move-btn" data-dir="out" data-part="<?=$pid?>" data-car="<?=$openCar?>" data-name="<?=h($ip['part_name'])?>" data-unit="<?=h(unitLabel((string)$ip['stock_unit']))?>" data-stock="<?=h((string)(float)$ip['stock_qty'])?>" title="<?=t('inv.stock_out_title')?>" aria-label="<?=t('inv.stock_out_title')?>">−</button><button type="button" class="btn2 stock-move-btn" data-dir="in" data-part="<?=$pid?>" data-car="<?=$openCar?>" data-name="<?=h($ip['part_name'])?>" data-unit="<?=h(unitLabel((string)$ip['stock_unit']))?>" data-stock="<?=h((string)(float)$ip['stock_qty'])?>" title="<?=t('inv.stock_in_title')?>" aria-label="<?=t('inv.stock_in_title')?>">＋</button><?php endif;?><span class="inventory-unit-label"><?=h(unitLabel((string)$ip['stock_unit']))?></span><span class="inventory-low-mark" title="<?=t('inv.low_note')?>"><?=t('inv.low_mark')?></span></div></td>
<td class="inv-extra" data-label="<?=t('inv.col_unit')?>"><input <?= $inventoryEditable?'':'readonly aria-readonly="true"' ?> class="inventory-edit inventory-unit" name="inventory_stock_unit[<?=$pid?>]" value="<?=h(unitLabel((string)$ip['stock_unit']))?>" maxlength="20" required></td>
<td class="inv-extra" data-label="<?=t('inv.col_reorder')?>"><input <?= $inventoryEditable?'':'readonly aria-readonly="true"' ?> class="inventory-edit inventory-reorder" name="inventory_reorder_level[<?=$pid?>]" inputmode="decimal" type="number" min="0" step="0.01" value="<?=$ip['reorder_level']!==null?h((string)(float)$ip['reorder_level']):''?>" placeholder="–"></td>
<td class="inv-extra" data-label="<?=h(purchasePriceLabel($app))?>"><div class="inventory-price-input"><input <?= $inventoryEditable?'':'readonly aria-readonly="true"' ?> class="inventory-edit inventory-price" name="inventory_purchase_price[<?=$pid?>]" inputmode="decimal" type="number" min="0" step="0.01" value="<?=$ip['purchase_price']!==null?h((string)(float)$ip['purchase_price']):''?>" placeholder="–"><span>€</span></div></td>
<td class="inv-extra" data-label="<?=t('inv.col_value')?>"><strong class="inventory-row-value"><?=$ip['purchase_price']!==null?h(money((float)$ip['stock_qty']*(float)$ip['purchase_price'])):'–'?></strong></td>
<td data-label="" class="inventory-actions"><button type="button" class="btn2 inventory-more" aria-expanded="false"><?=t('inv.more_details')?></button><a class="btn2 inventory-open" href="?car=<?=$openCar?>#varaosat" title="<?=t('inv.open_car_parts_title')?>"><?=t('inv.open_car_parts')?></a></td></tr>
<?php endforeach;?></tbody></table></div>
<?php if($inventoryEditable):?><input type="hidden" name="inventory_complete" value="1"><?php endif;?><div class="inventory-savebar"><div><strong id="inventoryVisibleCount"><?=t('inv.rows_visible',['n'=>count($inventoryParts)])?></strong><span class="tiny" id="inventoryDirtyText"><?=t('inv.no_unsaved')?></span></div><?php if($inventoryEditable):?><button class="btn" id="inventorySaveButton" type="submit"><?=t('inv.save_changes')?></button><?php endif;?></div><?php if($inventoryEditable):?></form><?php else:?></div><?php endif;?>
<?php endif;?></section>
<?php if($canMove):?>
<dialog id="stockMoveDialog" class="app-dialog"><form method="post" id="stockMoveForm"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="adjust_part_stock"><input type="hidden" name="return" value="inventory"><input type="hidden" name="part_id" id="smPart" value=""><input type="hidden" name="car_id" id="smCar" value="">
<h3 id="smTitle"><?=t('inv.sm_title')?></h3><div class="tiny" id="smInfo"></div>
<div class="sm-dir"><label class="sm-choice"><input type="radio" name="stock_direction" value="in" id="smIn"> <span><?=t('inv.sm_dir_in')?></span></label><label class="sm-choice"><input type="radio" name="stock_direction" value="out" id="smOut"> <span><?=t('inv.sm_dir_out')?></span></label></div>
<div class="grid grid2"><div><label><?=t('inv.sm_qty')?> <span id="smUnit"></span></label><input name="stock_qty" id="smQty" inputmode="decimal" type="number" min="0.01" step="0.01" required></div><div><label><?=t('inv.sm_note_label')?></label><input name="stock_note" id="smNote" maxlength="200" placeholder="<?=t('inv.sm_note_placeholder')?>"></div></div>
<div class="tiny"><?=t('inv.sm_help')?></div>
<div class="form-actions" style="margin-top:14px"><button class="btn" type="submit"><?=t('inv.sm_submit')?></button><button class="btn2" type="button" data-close-dialog><?=t('inv.cancel')?></button></div></form></dialog>
<?php endif;?>
<?php if($canAddPart&&$inventoryCars):$addItems=allItems($db,true);?>
<dialog id="addPartDialog" class="app-dialog app-dialog-wide"><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="add_part"><input type="hidden" name="return" value="inventory">
<h3><?=t('inv.ap_title')?></h3><div class="grid grid2"><div><label><?=t('inv.ap_car')?></label><select name="car_id" id="apCar" required><?php foreach($inventoryCars as $iid=>$iname):?><option value="<?=$iid?>"><?=h($iname?:t('inv.car_number',['n'=>$iid]))?></option><?php endforeach;?></select></div><div><label><?=t('inv.ap_item')?></label><select name="part_item_key"><option value=""><?=t('inv.ap_item_other')?></option><?php foreach($addItems as $ai):?><option value="<?=h($ai['item_key'])?>"><?=h($ai['label'])?></option><?php endforeach;?></select></div><div><label><?=t('inv.ap_name')?></label><input name="part_name" required></div><div><label><?=t('inv.ap_brand')?></label><input name="part_brand"></div><div><label><?=t('inv.ap_sku')?></label><input name="part_supplier_sku"></div><div><label><?=t('inv.ap_oem')?></label><input name="part_oem_number"></div></div>
<div style="margin-top:10px"><label><?=t('inv.ap_compat_label')?></label><div class="compat-grid"><?php foreach($inventoryCars as $iid=>$iname):?><label class="compat-choice" data-car="<?=$iid?>"><input type="checkbox" name="part_compatible_cars[]" value="<?=$iid?>"> <span><?=h($iname?:t('inv.car_number',['n'=>$iid]))?></span></label><?php endforeach;?></div><div class="tiny"><?=t('inv.ap_compat_help')?></div></div>
<div class="grid grid4" style="margin-top:10px"><div><label><?=t('inv.ap_initial_stock')?></label><input name="part_stock_qty" inputmode="decimal" value="0"></div><div><label><?=t('inv.col_unit')?></label><select name="part_stock_unit"><?php foreach(['pcs','l','set','pack'] as $uc):?><option value="<?=h($uc)?>"><?=h(unitLabel($uc))?></option><?php endforeach;?></select></div><div><label><?=t('inv.ap_shelf')?></label><input name="part_shelf_location"></div><div><label><?=t('inv.col_reorder')?></label><input name="part_reorder_level" inputmode="decimal"></div><div><label><?=h(purchasePriceLabel($app,t('inv.ap_purchase_price')))?></label><input name="part_purchase_price" inputmode="decimal"></div><div><label><?=t('inv.ap_notes')?></label><input name="part_notes"></div><div style="grid-column:span 2"><label><?=t('inv.ap_url')?></label><input type="url" name="part_url"></div></div>
<div class="form-actions" style="margin-top:14px"><button class="btn" type="submit"><?=t('inv.ap_submit')?></button><button class="btn2" type="button" data-close-dialog><?=t('inv.cancel')?></button></div></form></dialog>
<?php endif;?>
<?php
$stockRequested=filter_var($_GET['stock_page']??1,FILTER_VALIDATE_INT);$stockPartFilter=filter_var($_GET['stock_part']??0,FILTER_VALIDATE_INT);
$stockPartFilter=$stockPartFilter===false?0:max(0,$stockPartFilter);$stockTypeFilter=is_string($_GET['stock_type']??null)?trim($_GET['stock_type']):'';
$stockEvents=inventoryHistoryPage($db,$stockRequested===false?1:$stockRequested,$stockPartFilter,$stockTypeFilter);
$stockTypes=$db->query('SELECT DISTINCT event_type FROM inventory_transactions ORDER BY event_type')->fetchAll(PDO::FETCH_COLUMN);
$stockHistoryLink=static fn(int $page):string=>'?'.http_build_query(['view'=>'inventory','stock_page'=>$page,'stock_part'=>$stockPartFilter,'stock_type'=>$stockTypeFilter]).'#varastotapahtumat';
?>
<section class="section panel" id="stockHistoryPanel"><details class="clean" id="varastotapahtumat" <?=isset($_GET['stock_page'])?'open':''?>><summary><?=t('inv.events_summary',['n'=>$stockEvents['all_total']])?></summary><div class="inside">
<p class="tiny"><?=t('inv.events_help')?></p>
<?php if(!empty($app['inventory_history_cleared_at'])):?><p class="tiny stock-history-last-clear"><?=t('inv.events_last_clear',['date'=>h(date('d.m.Y H:i',strtotime($app['inventory_history_cleared_at']))),'by'=>h($app['inventory_history_cleared_by']??''),'n'=>(int)($app['inventory_history_cleared_count']??0)])?></p><?php endif;?>
<form method="get" class="stock-history-filters"><input type="hidden" name="view" value="inventory"><input type="hidden" name="stock_page" value="1"><div class="grid grid2"><div><label><?=t('inv.events_part_label')?></label><select name="stock_part"><option value="0"><?=t('inv.events_all_parts')?></option><?php foreach($inventoryParts as $sp):?><option value="<?=(int)$sp['id']?>" <?=$stockPartFilter===(int)$sp['id']?'selected':''?>><?=h(trim($sp['part_name'].' · '.$sp['brand'].' '.$sp['supplier_sku']))?></option><?php endforeach;?></select></div><div><label><?=t('inv.events_type_label')?></label><select name="stock_type"><option value=""><?=t('inv.events_all_types')?></option><?php foreach($stockTypes as $type):?><option value="<?=h($type)?>" <?=$stockTypeFilter===$type?'selected':''?>><?=h(inventoryEventLabel($type))?></option><?php endforeach;?></select></div></div><div class="form-actions"><button class="btn2"><?=t('inv.events_filter')?></button><a class="btn2" href="?view=inventory&stock_page=1#varastotapahtumat"><?=t('inv.events_clear_filter')?></a></div></form>
<p class="tiny stock-history-count"><?=$stockEvents['total']?t('inv.events_showing',['from'=>$stockEvents['offset']+1,'to'=>$stockEvents['offset']+count($stockEvents['rows']),'total'=>$stockEvents['total']]):t('inv.events_none')?></p>
<?php if($stockEvents['rows']):?><table class="stock-events-table"><thead><tr><th><?=t('inv.events_col_time')?></th><th><?=t('inv.col_part')?></th><th><?=t('inv.events_col_event')?></th><th><?=t('inv.events_col_change')?></th><th><?=t('inv.events_col_after')?></th><th><?=t('inv.events_col_note')?></th></tr></thead><tbody>
<?php foreach($stockEvents['rows'] as $stx):?><tr class="stock-event-row"><td data-label="<?=t('inv.events_col_time')?>"><?=h(date('d.m.Y H:i',strtotime($stx['created_at'])))?></td><td data-label="<?=t('inv.col_part')?>"><a href="?car=<?=(int)$stx['car_id']?>#varaosat"><strong><?=h($stx['part_name'])?></strong></a><div class="tiny"><?=h(trim($stx['brand'].' '.$stx['supplier_sku']))?></div></td><td data-label="<?=t('inv.events_col_event')?>"><?=h(inventoryEventLabel($stx['event_type']))?></td><td data-label="<?=t('inv.events_col_change')?>"><strong><?=((float)$stx['quantity_change']>0?'+':'')?><?=h(dec((float)$stx['quantity_change'],2).' '.unitLabel((string)$stx['stock_unit']))?></strong></td><td data-label="<?=t('inv.events_col_after')?>"><?=h(dec((float)$stx['stock_after'],2).' '.unitLabel((string)$stx['stock_unit']))?></td><td data-label="<?=t('inv.events_col_note')?>" class="stock-events-note"><?=h(noteLabel((string)$stx['note']))?></td></tr><?php endforeach;?></tbody></table><?php endif;?>
<?php if($stockEvents['pages']>1):?><nav class="form-actions" aria-label="<?=t('inv.events_pages_label')?>"><?php if($stockEvents['page']>1):?><a class="btn2" href="<?=h($stockHistoryLink(1))?>"><?=t('inv.events_newest')?></a><a class="btn2" href="<?=h($stockHistoryLink($stockEvents['page']-1))?>"><?=t('inv.events_prev')?></a><?php endif;?><span class="tiny"><?=t('inv.events_page',['page'=>$stockEvents['page'],'pages'=>$stockEvents['pages']])?></span><?php if($stockEvents['page']<$stockEvents['pages']):?><a class="btn2" href="<?=h($stockHistoryLink($stockEvents['page']+1))?>"><?=t('inv.events_next')?></a><a class="btn2" href="<?=h($stockHistoryLink($stockEvents['pages']))?>"><?=t('inv.events_oldest')?></a><?php endif;?></nav><?php endif;?>
<?php if(canAction('clear_inventory_history')):?><details class="clean" style="margin-top:18px"><summary><?=t('inv.clear_summary')?></summary><div class="inside"><p class="tiny"><?=t('inv.clear_help')?></p>
<form method="post" class="clear-stock-history-form"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="clear_inventory_history"><input type="hidden" name="stock_history_up_to" value="<?=$stockEvents['last_id']?>"><label><input type="checkbox" name="stock_history_confirm" value="1" required> <?=t('inv.clear_confirm')?></label><div class="form-actions"><button class="danger"><?=t('inv.clear_button')?></button></div><p class="tiny"><?=t('inv.clear_help2')?></p></form></div></details><?php endif;?>
</div></details></section>
<?php if($inventoryParts):?><?php endif;?>
