<?php
declare(strict_types=1);
$searchQ=trim((string)($_GET['q']??''));$sr=globalSearch($db,$searchQ,$app);$srTotal=array_sum(array_map('count',$sr));
?>
<section class="hero panel"><div><div class="eyebrow"><?=t('search.eyebrow')?></div><h1><?=t('search.title')?></h1><form method="get" class="search-page-form" role="search"><input type="hidden" name="view" value="search"><label for="sq" class="sr-only"><?=t('search.label')?></label><input id="sq" type="search" name="q" value="<?=h($searchQ)?>" placeholder="<?=h(t('search.placeholder'))?>" autofocus><button class="btn"><?=t('search.button')?></button></form></div></section>
<?php if(mb_strlen($searchQ)<2):?><section class="section panel"><div class="empty"><?=t('search.too_short')?></div></section>
<?php elseif($srTotal===0):?><section class="section panel"><div class="empty"><?=t('search.none',['q'=>h($searchQ)])?></div></section>
<?php else:?>
<?php if($sr['cars']):?><section class="section panel"><h2><?=t('search.cars')?> <span class="badge"><?=count($sr['cars'])?></span></h2><div class="search-list"><?php foreach($sr['cars'] as $c):?><a class="search-row" href="?car=<?=(int)$c['id']?>"><strong><?=h(carName($c))?></strong><span class="tiny"><?=h(trim(($c['owner']??'').' '.($c['year']?'· '.$c['year']:'')))?></span></a><?php endforeach;?></div></section><?php endif;?>
<?php if($sr['customers']):?><section class="section panel"><h2><?=t('search.customers')?> <span class="badge"><?=count($sr['customers'])?></span></h2><div class="search-list"><?php foreach($sr['customers'] as $c):?><a class="search-row" href="?view=customers&customer=<?=(int)$c['id']?>"><strong><?=h($c['name'])?></strong><span class="tiny"><?=h(trim($c['customer_number'].' · '.$c['phone'].' · '.$c['email'],' ·'))?></span></a><?php endforeach;?></div></section><?php endif;?>
<?php if($sr['services']):?><section class="section panel"><h2><?=t('search.services')?> <span class="badge"><?=count($sr['services'])?></span></h2><div class="search-list"><?php foreach($sr['services'] as $s):?><a class="search-row" href="?car=<?=(int)$s['car_id']?>#historia"><strong><?=h($s['title'])?></strong><span class="tiny"><?=h(fiDate($s['service_date']).' · '.carName($s))?></span></a><?php endforeach;?></div></section><?php endif;?>
<?php if($sr['invoices']):?><section class="section panel"><h2><?=t('search.invoices')?> <span class="badge"><?=count($sr['invoices'])?></span></h2><div class="search-list"><?php foreach($sr['invoices'] as $i):?><a class="search-row" href="?invoice=<?=(int)$i['id']?>"><strong><?=h($i['invoice_number'])?></strong><span class="tiny"><?=h(fiDate($i['issue_date']).' · '.($i['customer_name']?:'—').' · '.invoiceStatusLabel((string)$i['status']))?></span></a><?php endforeach;?></div></section><?php endif;?>
<?php if($sr['parts']):?><section class="section panel"><h2><?=t('search.parts')?> <span class="badge"><?=count($sr['parts'])?></span></h2><div class="search-list"><?php foreach($sr['parts'] as $p):?><a class="search-row" href="?view=inventory&q=<?=h(rawurlencode((string)$p['part_name']))?>"><strong><?=h($p['part_name'])?></strong><span class="tiny"><?=h(trim($p['brand'].' · '.$p['supplier_sku'].' · '.dec((float)$p['stock_qty'],2).' '.unitLabel((string)$p['stock_unit']),' ·'))?></span></a><?php endforeach;?></div></section><?php endif;?>
<?php endif;?>
