<?php
declare(strict_types=1);
 $catalogItems=allItems($db); ?>
<section class="hero panel"><div><div class="eyebrow"><?=t('set.eyebrow')?></div><h1><?=t('set.title')?></h1><div class="sub"><?=t('set.intro')?></div></div></section>
<?php $settingsTabs=['yleiset'=>[t('set.tab_general'),'yleiset'],'huolto'=>[t('set.tab_catalog'),'kohteet']];if(mechanicsEnabled($app))$settingsTabs['mekaanikot']=[t('set.mechanics'),'mekaanikot'];$settingsTabs['kayttajat']=[t('set.tab_users'),'kayttajat'];$settingsTabs['tarkistus']=[t('set.tab_check'),'datacheck'];$settingsTabs['turva']=[t('set.tab_security'),'backup']; ?>
<nav class="settings-tabs" id="settingsTabs" aria-label="<?=t('set.tabs_aria')?>"><?php foreach($settingsTabs as $tk=>[$tl,$ta]):?><a href="#<?=h($ta)?>" data-tab-link="<?=h($tk)?>"><?=h($tl)?><?php if($tk==='tarkistus'&&count($dataIssues)):?> <span class="badge"><?=count($dataIssues)?></span><?php endif;?></a><?php endforeach;?></nav>
<div class="settings-panels" id="settingsPanels">
<section class="section panel" id="yleiset" data-tab="yleiset"><h2><?=t('set.general_title')?></h2><form method="post" enctype="multipart/form-data" id="appSettingsForm" data-savebar><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="save_app_settings"><div class="grid grid4"><div><label><?=t('set.app_name')?></label><input name="shop_name" value="<?=h($appName)?>" required><div class="tiny"><?=t('set.app_name_help')?></div></div><div><label><?=t('set.language')?></label><select name="language"><?php foreach(i18nLanguageOptions() as $lc=>$ln):?><option value="<?=h($lc)?>" <?=i18nValidLanguage((string)($app['language']??''))===$lc?'selected':''?>><?=h($ln)?></option><?php endforeach;?></select><div class="tiny"><?=t('set.language_help')?></div></div><div><label><?=t('set.theme')?></label><select name="theme"><option value="dark" <?=$theme==='dark'?'selected':''?>><?=t('set.theme_dark')?></option><option value="mid" <?=$theme==='mid'?'selected':''?>><?=t('set.theme_mid')?></option><option value="light" <?=$theme==='light'?'selected':''?>><?=t('set.theme_light')?></option></select></div><div><label><?=t('set.price_input_mode')?></label><select name="price_input_mode" id="priceInputMode"><option value="net" <?=priceInputMode($app)==='net'?'selected':''?>><?=t('set.price_mode_net')?></option><option value="gross" <?=priceInputMode($app)==='gross'?'selected':''?>><?=t('set.price_mode_gross',['vat'=>h(dec(appVatRate($app),1))])?></option></select><div class="tiny"><?=t('set.price_mode_help')?></div><div class="tiny"><?=t('set.price_mode_change_help')?></div></div><div><label id="hourlyRateLabel"><?=h(priceInputLabel($app,t('set.default_hourly_rate')))?></label><input id="settingHourlyRate" name="hourly_rate" inputmode="decimal" value="<?=h(str_replace('.',',',(string)(priceInputFromNet((float)($app['hourly_rate']??65),$app)??65)))?>"></div><div><label><?=t('set.vat_percent')?></label><input id="settingVatRate" name="vat_rate" inputmode="decimal" value="<?=h(str_replace('.',',',$app['vat_rate']??'25.5'))?>"><div class="tiny"><?=t('set.vat_help')?></div></div><div><label><?=t('set.payment_days')?></label><input name="payment_days" inputmode="numeric" value="<?=h($app['payment_days']??'14')?>"></div></div><div style="margin-top:20px;padding:14px;border:1px solid var(--line);border-radius:14px;background:var(--panel2)"><h3 style="margin-top:0"><?=t('set.home_texts_title')?></h3><div class="grid grid2"><div><label><?=t('set.home_title')?></label><input name="home_title" maxlength="120" value="<?=h(homeTitleText($app))?>" required><div class="tiny"><?=t('set.home_title_help')?></div></div><div><label><?=t('set.home_subtitle')?></label><textarea name="home_subtitle" maxlength="500" placeholder="<?=t('set.home_subtitle_placeholder')?>"><?=h(homeSubtitleText($app))?></textarea><div class="tiny"><?=t('set.home_subtitle_help')?></div></div></div></div>
<?php $currentLogo=(string)($app['logo_path']??'');$hasCurrentLogo=$currentLogo!==''&&logoAbsolutePath($currentLogo)&&is_file((string)logoAbsolutePath($currentLogo));$logoVariants=$hasCurrentLogo?ensureLogoDerivatives($currentLogo):['header'=>null,'web'=>null];$logoOptimizerReady=logoOptimizationAvailable();?>
<div style="margin-top:20px;padding:14px;border:1px solid var(--line);border-radius:14px;background:var(--panel2)"><div class="grid grid3"><div><label><?=t('set.logo_label')?></label><input type="file" name="company_logo" accept="image/jpeg,image/png,image/webp"><div class="tiny"><?=t('set.logo_help')?></div><?php if(!$logoOptimizerReady):?><div class="flash warn" style="margin:10px 0 0"><?=t('set.logo_no_optimizer')?></div><?php endif;?></div><div><?php if($hasCurrentLogo):?><label><?=t('set.logo_current')?></label><div style="padding:10px;background:#fff;border-radius:10px;display:inline-block"><img src="<?=h(logoUrl($currentLogo))?>" alt="<?=t('set.logo_alt')?>" style="display:block;max-width:220px;max-height:90px;width:auto;height:auto"></div><div class="tiny" style="margin-top:8px"><?=t('set.logo_size_orig',['size'=>h(logoFileSizeText($currentLogo))])?><br><?=t('set.logo_size_web',['size'=>h(logoFileSizeText($logoVariants['web']))])?><br><?=t('set.logo_size_header',['size'=>h(logoFileSizeText($logoVariants['header']))])?></div><?php else:?><label><?=t('set.logo_current')?></label><div class="tiny"><?=t('set.logo_none')?></div><?php endif;?></div><div><label><?=t('set.logo_where')?></label><label style="color:var(--text)"><input type="checkbox" name="show_logo_invoice" value="1" <?=($app['show_logo_invoice']??'1')==='1'?'checked':''?>> <?=t('set.logo_on_invoice')?></label><label style="margin-top:7px;color:var(--text)"><input type="checkbox" name="show_logo_service_print" value="1" <?=($app['show_logo_service_print']??'1')==='1'?'checked':''?>> <?=t('set.logo_on_service_print')?></label><label style="margin-top:7px;color:var(--text)"><input type="checkbox" name="show_logo_car_history" value="1" <?=($app['show_logo_car_history']??'1')==='1'?'checked':''?>> <?=t('set.logo_on_car_history')?></label><label style="margin-top:7px;color:var(--text)"><input type="checkbox" name="show_logo_all_history" value="1" <?=($app['show_logo_all_history']??'1')==='1'?'checked':''?>> <?=t('set.logo_on_all_history')?></label><label style="margin-top:7px;color:var(--text)"><input type="checkbox" name="show_logo_header" value="1" <?=($app['show_logo_header']??'0')==='1'?'checked':''?>> <?=t('set.logo_on_header')?></label><?php if($hasCurrentLogo):?><label style="margin-top:12px;color:var(--bad)"><input type="checkbox" name="remove_logo" value="1"> <?=t('set.logo_remove')?></label><div class="tiny"><?=t('set.logo_remove_help')?></div><?php endif;?></div></div></div>
<h3 class="set-h"><?=t('set.features_title')?></h3><div class="feature-grid"><label class="feature-toggle"><input type="checkbox" name="feature_invoicing" value="1" <?=invoicingEnabled($app)?'checked':''?>><span><strong><?=t('set.feat_invoicing')?></strong><small><?=t('set.feat_invoicing_help')?></small></span></label><label class="feature-toggle"><input type="checkbox" name="feature_mechanics" value="1" <?=mechanicsEnabled($app)?'checked':''?>><span><strong><?=t('set.feat_mechanics')?></strong><small><?=t('set.feat_mechanics_help')?></small></span></label><label class="feature-toggle"><input type="checkbox" name="feature_customers" value="1" <?=customersEnabled($app)?'checked':''?>><span><strong><?=t('set.feat_customers')?></strong><small><?=t('set.feat_customers_help')?></small></span></label><label class="feature-toggle"><input type="checkbox" name="feature_time_tracking" value="1" <?=timeTrackingEnabled($app)?'checked':''?>><span><strong><?=t('set.feat_time_tracking')?></strong><small><?=t('set.feat_time_tracking_help')?></small></span></label><label class="feature-toggle"><input type="checkbox" name="feature_inventory" value="1" <?=inventoryEnabled($app)?'checked':''?>><span><strong><?=t('set.feat_inventory')?></strong><small><?=t('set.feat_inventory_help')?></small></span></label></div><div class="tiny" style="margin-top:10px"><?=t('set.features_note')?></div>
<details class="clean" style="margin-top:20px" <?=invoicingEnabled($app)?'open':''?>><summary><?=t('set.business_summary')?><?php if(invoicingEnabled($app)&&trim((string)($app['business_id']??''))===''):?> <span class="badge warnbadge"><?=t('set.business_id_missing')?></span><?php endif;?></summary><div class="inside grid grid3"><div><label><?=t('set.business_id')?></label><input name="business_id" value="<?=h($app['business_id']??'')?>"></div><div><label><?=t('set.phone')?></label><input name="shop_phone" value="<?=h($app['shop_phone']??'')?>"></div><div><label><?=t('set.address')?></label><textarea name="shop_address"><?=h($app['shop_address']??'')?></textarea></div><div><label><?=t('set.email')?></label><input name="shop_email" value="<?=h($app['shop_email']??'')?>"></div><div><label>IBAN</label><input name="iban" value="<?=h($app['iban']??'')?>"><label style="margin-top:8px">BIC</label><input name="bic" value="<?=h($app['bic']??'')?>"></div><div><label style="color:var(--text)"><input type="checkbox" name="mobilepay_enabled" value="1" <?=($app['mobilepay_enabled']??'0')==='1'?'checked':''?>> <?=t('set.mobilepay_enabled')?></label><label style="margin-top:8px"><?=t('set.mobilepay_number')?></label><input name="mobilepay_number" value="<?=h($app['mobilepay_number']??'')?>" placeholder="<?=t('set.mobilepay_number_placeholder')?>"><label style="margin-top:8px"><?=t('set.mobilepay_name')?></label><input name="mobilepay_name" value="<?=h($app['mobilepay_name']??'')?>" placeholder="<?=t('set.mobilepay_name_placeholder')?>"><div class="tiny"><?=t('set.mobilepay_help')?></div></div><div class="markup-box" style="grid-column:1/-1"><h3 class="set-h" style="margin-top:6px"><?=t('set.markup_title')?></h3><div class="grid grid3"><div><label style="color:var(--text)"><input type="checkbox" name="parts_markup_enabled" value="1" <?=($app['parts_markup_enabled']??'0')==='1'?'checked':''?>> <?=t('set.markup_enabled')?></label></div><div><label><?=t('set.markup_percent')?></label><input name="parts_markup_percent" inputmode="decimal" value="<?=h(str_replace('.',',',(string)($app['parts_markup_percent']??'15')))?>"></div></div><div class="tiny"><?=t('set.markup_help',['mode'=>h(priceInputMode($app)==='gross'?t('set.mode_incl_vat'):t('set.mode_net'))])?></div></div></div></details><div class="form-actions savebar"><span class="savebar-note" hidden><?=t('set.unsaved_changes')?></span><button class="btn"><?=t('set.save_settings')?></button></div></form></section>
<?php if(!mechanicsEnabled($app) && count($mechanicsAll)>0):?><div class="flash warn"><?=t('set.mechanics_disabled_notice',['n'=>count($mechanicsAll)])?></div><?php endif;?>
<?php if(mechanicsEnabled($app)):?>
<section class="section panel" id="mekaanikot" data-tab="mekaanikot"><div class="sectionhead"><div><div class="eyebrow"><?=t('set.shop_eyebrow')?></div><h2><?=t('set.mechanics')?></h2><div class="tiny"><?=t('set.mechanics_help')?></div></div><span class="badge"><?=t('set.n_active',['n'=>count($activeMechanics)])?></span></div>
<details class="clean"><summary><?=t('set.add_mechanic')?></summary><div class="inside"><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="add_mechanic"><div class="grid grid4"><div><label><?=t('set.name')?></label><input name="mechanic_name" required placeholder="<?=t('set.mechanic_name_placeholder')?>"></div><div><label style="margin-top:28px"><input type="checkbox" name="mechanic_active" value="1" checked> <?=t('set.active')?></label></div><div><label style="margin-top:28px"><input type="checkbox" name="mechanic_default" value="1"> <?=t('set.default_mechanic_short')?></label></div><div style="align-self:end"><button class="btn"><?=t('set.add_mechanic')?></button></div></div></form></div></details>
<div style="margin-top:16px"><?php $mechUse=[];foreach($db->query("SELECT mechanic_id,COUNT(*) c FROM services WHERE mechanic_id IS NOT NULL AND mechanic_id<>0 GROUP BY mechanic_id")->fetchAll() as $mu)$mechUse[(int)$mu['mechanic_id']]=(int)$mu['c'];$mechUsers=[];foreach($db->query("SELECT mechanic_id,COUNT(*) c FROM auth_users WHERE mechanic_id<>0 GROUP BY mechanic_id")->fetchAll() as $mu)$mechUsers[(int)$mu['mechanic_id']]=(int)$mu['c'];?><?php if(!$mechanicsAll):?><div class="empty"><?=t('set.mechanics_none')?></div><?php else:foreach($mechanicsAll as $m):$mUse=$mechUse[(int)$m['id']]??0;$mUsers=$mechUsers[(int)$m['id']]??0;$mIsMuu=isMechanicOther((string)$m['name_raw']);?><div class="mech-card"><form method="post" class="grid grid4"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="update_mechanic"><input type="hidden" name="mechanic_id" value="<?=(int)$m['id']?>"><div><label><?=t('set.name')?></label><input name="mechanic_name" value="<?=h($m['name'])?>" required></div><div><label style="margin-top:28px"><input type="checkbox" name="mechanic_active" value="1" <?=(int)$m['active']===1?'checked':''?>> <?=t('set.active')?></label></div><div><label style="margin-top:28px"><input type="checkbox" name="mechanic_default" value="1" <?=(int)$m['is_default']===1?'checked':''?>> <?=t('set.default_mechanic_short')?></label></div><div style="align-self:end"><button class="btn2"><?=t('set.save')?></button></div></form><form method="post" class="mech-del" onsubmit="return confirm(this.dataset.msg);" data-msg="<?=h(t('set.mech_del_q',['name'=>$m['name']]).($mUse>0?' '.t('set.mech_del_used',['n'=>$mUse]).' '.t($mIsMuu?'set.mech_del_used_muu':'set.mech_del_used_other'):'').($mUsers>0?' '.t('set.mech_del_users',['n'=>$mUsers]):'').' '.t('set.mech_del_irreversible'))?>"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="delete_mechanic"><input type="hidden" name="mechanic_id" value="<?=(int)$m['id']?>"><input type="hidden" name="usage_count" value="<?=$mUse?>"><input type="hidden" name="delete_confirm" value="1"><span class="tiny"><?=$mUse>0?t('set.mech_marked',['n'=>$mUse]):t('set.mech_no_jobs')?><?=$mUsers>0?' · '.t('set.mech_users_default',['n'=>$mUsers]):''?></span><button class="danger"><?=t('set.delete_mechanic')?></button></form></div><?php endforeach;endif;?></div></section>
<?php endif;?>
<section class="section panel" id="kohteet" data-tab="huolto"><div class="sectionhead"><div><div class="eyebrow"><?=t('set.catalog_eyebrow')?></div><h2><?=t('set.catalog_title')?></h2><div class="tiny"><?=t('set.catalog_help')?></div></div></div>
<details class="clean"><summary><?=t('set.add_catalog_summary')?></summary><div class="inside"><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="add_catalog_item"><div class="grid grid4"><div><label><?=t('set.name')?></label><input name="item_label" placeholder="<?=t('set.item_label_placeholder')?>" required></div><div><label><?=t('set.group')?></label><input name="item_section" placeholder="<?=t('set.item_section_placeholder')?>"></div><div><label><?=t('set.item_kind')?></label><select name="item_kind"><?php foreach(itemKinds() as $ik=>$il):?><option value="<?=h($ik)?>"><?=h($il)?></option><?php endforeach;?></select></div><div style="align-self:end"><button class="btn"><?=t('set.add_catalog_item')?></button></div></div></form></div></details>
<div class="cat-groups" style="margin-top:20px"><div class="tiny" style="margin-bottom:10px"><?=t('set.catalog_legend')?></div><?php $catGroups=[];foreach($catalogItems as $it){$gn=trim((string)$it['section']);$catGroups[$gn!==''?$gn:t('vocab.section.other')][]=$it;}
foreach($catGroups as $gName=>$gItems):$gOff=count(array_filter($gItems,fn($x)=>(int)$x['active']!==1));?>
<details class="clean cat-group"><summary><?=h($gName)?> <span class="badge"><?=t('set.n_items',['n'=>count($gItems)])?></span><?=$gOff?' <span class="badge warnbadge">'.t('set.n_off',['n'=>$gOff]).'</span>':''?></summary><div class="inside">
<div class="cat-head"><span><?=t('set.name')?></span><span><?=t('set.group')?></span><span><?=t('set.col_type')?></span><span><?=t('set.col_status')?></span><span></span></div>
<?php foreach($gItems as $it):?><form method="post" class="cat-row<?=(int)$it['active']===1?'':' is-off'?>" id="kohde-<?=h($it['item_key'])?>"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="update_catalog_item"><input type="hidden" name="item_key" value="<?=h($it['item_key'])?>"><div class="cat-name"><label class="row-lbl"><?=t('set.name')?></label><input name="item_label" value="<?=h($it['label'])?>" required><span class="tiny"><span class="badge"><?=(int)$it['is_custom']===1?t('set.cat_custom'):t('set.cat_builtin')?></span> <?=t('set.cat_key_locked',['key'=>h($it['item_key'])])?></span></div><div><label class="row-lbl"><?=t('set.group')?></label><input name="item_section" value="<?=h($it['section'])?>"></div><div><label class="row-lbl"><?=t('set.item_kind')?></label><select name="item_kind"><?php foreach(itemKinds() as $ik=>$il):?><option value="<?=h($ik)?>" <?=($it['item_kind']??'generic')===$ik?'selected':''?>><?=h($il)?></option><?php endforeach;?></select></div><div class="cat-active"><label><input type="checkbox" name="active" value="1" <?=(int)$it['active']===1?'checked':''?>> <?=t('set.active')?></label></div><div class="cat-save"><button class="btn2"><?=t('set.save')?></button></div></form><?php endforeach;?>
</div></details>
<?php endforeach;?></div></section>
<section class="section panel" id="kayttajat" data-tab="kayttajat"><h2><?=t('set.users_title')?></h2><?php if((int)$db->query("SELECT COUNT(*) FROM auth_users WHERE role='admin' AND active=1")->fetchColumn()<2):?><div class="flash warn"><?=t('set.only_one_admin')?></div><?php endif;?><p><?=t('set.roles_intro')?></p><details class="clean sub-details"><summary><?=t('set.roles_more_summary')?></summary><div class="inside"><p class="tiny"><?=t('set.roles_more')?></p></div></details>
<details class="clean"><summary><?=t('set.create_user_summary')?></summary><div class="inside"><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="add_user"><div class="grid grid3"><div><label><?=t('set.username')?></label><input name="username" required minlength="3" maxlength="64" autocomplete="off"></div><div><label><?=t('set.name')?></label><input name="display_name" required maxlength="100"></div><div><label><?=t('set.permissions')?></label><select name="role"><?php foreach(['viewer','editor','admin'] as $role):?><option value="<?=h($role)?>"><?=h(roleLabel($role))?></option><?php endforeach;?></select></div><div><label><?=t('set.temp_password_min')?></label><input type="password" name="new_password" required minlength="12" autocomplete="new-password"></div><div><label><?=t('set.password_again')?></label><input type="password" name="password_confirm" required autocomplete="new-password"></div><div><label><?=t('set.user_default_mechanic')?></label><select name="mechanic_id"><option value="0"><?=t('set.shop_default_no_link')?></option><?php foreach($activeMechanics as $m):?><option value="<?=(int)$m['id']?>"><?=h($m['name'])?></option><?php endforeach;?></select></div></div><div class="form-actions"><button class="btn"><?=t('set.create_user')?></button></div><p class="tiny"><?=t('set.create_user_help')?></p></form></div></details>
<?php $activeAdminCount=(int)$db->query("SELECT COUNT(*) FROM auth_users WHERE role='admin' AND active=1")->fetchColumn();foreach($db->query('SELECT id,username,display_name,role,active,mechanic_id,last_login_at,force_password_change FROM auth_users ORDER BY active DESC,username')->fetchAll() as $user):$isLastAdmin=$user['role']==='admin'&&(int)$user['active']===1&&$activeAdminCount<=1; ?>
<details class="clean user-row<?=(int)$user['active']?'':' is-off'?>" id="user-<?=(int)$user['id']?>"><summary><span class="ur-main"><strong><?=h($user['username'])?></strong> <span class="badge"><?=h(roleLabel($user['role']))?></span><?=(int)$user['active']?'':' <span class="badge warnbadge">'.t('set.badge_off').'</span>'?><?=(int)$user['id']===(int)$currentUser['id']?' <span class="badge">'.t('set.badge_you').'</span>':''?></span><span class="ur-meta"><?=h($user['display_name'])?> · <?=h($user['last_login_at']?t('set.last_login_at',['date'=>date('d.m.Y H:i',strtotime($user['last_login_at']))]):t('set.never_logged_in'))?><?=(int)$user['force_password_change']?' · '.t('set.pw_change_required'):''?></span><span class="ur-edit btn2"><?=t('set.edit')?></span></summary><div class="inside"><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="update_user"><input type="hidden" name="user_id" value="<?=(int)$user['id']?>"><div class="grid grid4 user-grid"><div><label><?=t('set.name')?></label><input name="display_name" value="<?=h($user['display_name'])?>" required maxlength="100"></div><div><label><?=t('set.permissions')?></label><select name="role"><?php foreach(['viewer','editor','admin'] as $role):?><option value="<?=h($role)?>" <?=$role===$user['role']?'selected':''?>><?=h(roleLabel($role))?></option><?php endforeach;?></select></div><div><label><?=t('set.default_mechanic')?></label><select name="mechanic_id"><option value="0"><?=t('set.shop_default_no_link')?></option><?php foreach($mechanicsAll as $m):if(!(int)$m['active']&&(int)$user['mechanic_id']!==(int)$m['id'])continue;?><option value="<?=(int)$m['id']?>" <?=(int)$user['mechanic_id']===(int)$m['id']?'selected':''?>><?=h($m['name'])?><?=(int)$m['active']?'':' · '.t('set.badge_off')?></option><?php endforeach;?></select></div><div class="user-save"><label><input type="checkbox" name="user_active" value="1" <?=(int)$user['active']?'checked':''?>> <?=t('set.active')?></label><button class="btn2"><?=t('set.save_user')?></button></div></div><p class="tiny"><?=t('set.last_login_line',['value'=>h($user['last_login_at']?date('d.m.Y H:i',strtotime($user['last_login_at'])):t('set.no_login_yet'))])?><?=(int)$user['force_password_change']?' · '.t('set.pw_change_required'):''?></p></form>
<?php if((int)$user['id']!==(int)$currentUser['id']):?><details class="clean sub-details"><summary><?=t('set.reset_password_summary')?></summary><div class="inside"><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="reset_user_password"><input type="hidden" name="user_id" value="<?=(int)$user['id']?>"><div class="grid grid2"><div><label><?=t('set.new_temp_password')?></label><input type="password" name="new_password" required minlength="12" autocomplete="new-password"></div><div><label><?=t('set.password_again')?></label><input type="password" name="password_confirm" required autocomplete="new-password"></div></div><div class="form-actions"><button class="btn2"><?=t('set.reset_password_btn')?></button></div><p class="tiny"><?=t('set.reset_password_help')?></p></form></div></details><?php endif;?>
<form method="post" class="form-actions" style="margin-top:16px" onsubmit="return confirm('<?=strtr(addcslashes(t('set.user_del_confirm'),"'\\"),['{name}'=>"'+this.elements.confirm_username.value+'"])?>');"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="delete_user"><input type="hidden" name="user_id" value="<?=(int)$user['id']?>"><input type="hidden" name="delete_confirm" value="1"><input type="hidden" name="confirm_username" value="<?=h($user['username'])?>"><button class="danger" <?=$isLastAdmin?'disabled':''?>><?=t('set.delete_user')?></button></form>
<?php if($isLastAdmin):?><p class="tiny"><?=t('set.last_admin_note')?></p><?php elseif((int)$user['id']===(int)$currentUser['id']):?><p class="tiny"><?=t('set.own_delete_note')?></p><?php endif;?></div></details>
<?php endforeach;?>
</section>
<section class="section panel" id="datacheck" data-tab="tarkistus"><div class="sectionhead"><div><div class="eyebrow"><?=t('set.check_eyebrow')?></div><h2><?=t('set.check_title')?></h2><div class="tiny"><?=t('set.check_help')?></div></div><span class="badge"><?=t('set.n_issues',['n'=>count($dataIssues)])?></span></div><?php if(!$dataIssues):?><div class="flash ok"><?=t('set.check_ok')?></div><?php else:
$issueGroupDefs=['error'=>['⛔',t('set.issue_errors')],'img'=>['🖼',t('set.issue_images')],'warn'=>['⚠',t('set.issue_warnings')],'info'=>['ℹ',t('set.issue_notes')]];$issueGroups=[];foreach($dataIssues as $di)$issueGroups[dataIssueGroup($di)][]=$di;
foreach($issueGroupDefs as $gk=>[$gi,$gl]):if(empty($issueGroups[$gk]))continue;$gItems=$issueGroups[$gk];?>
<details class="clean issue-group <?=h($gk)?>" <?=($gk==='error'||count($gItems)<=3)?'open':''?>><summary><?=$gi?> <?=h($gl)?> <span class="badge"><?=count($gItems)?></span></summary><div class="inside">
<?php if($gk!=='error'&&count($gItems)>1):?><form method="post" class="form-actions" onsubmit="return confirm('<?=strtr(addcslashes(t('set.accept_all_confirm'),"'\\"),['{n}'=>count($gItems),'{group}'=>h($gl)])?>');"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="accept_data_issues"><input type="hidden" name="issue_group" value="<?=h($gk)?>"><button class="btn2"><?=t('set.accept_all',['n'=>count($gItems)])?></button></form><?php endif;?>
<div class="checklist"><?php foreach($gItems as $di):?><div class="checkitem <?=h($di['level'])?>"><div style="flex:1"><strong><?=h($di['level']==='error'?'⛔ ':($di['level']==='warn'?'⚠ ':'ℹ '))?><?=h($di['title'])?></strong><div class="tiny" style="margin-top:4px"><?=h($di['detail'])?></div></div><div class="form-actions" style="margin:0"><?php if($di['url']):?><a class="btn2" href="<?=h($di['url'])?>"><?=t('set.open')?></a><?php endif;?><?php if($di['level']!=='error'):?><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="accept_data_issue"><input type="hidden" name="issue_key" value="<?=h($di['key'])?>"><input type="hidden" name="issue_title" value="<?=h($di['title'])?>"><input type="hidden" name="issue_detail" value="<?=h($di['detail'])?>"><input type="hidden" name="issue_note" value="@accepted_deviation"><button class="btn2"><?=t('set.accept_issue')?></button></form><?php endif;?></div></div><?php endforeach;?></div></div></details>
<?php endforeach;endif;?><?php if($acceptedIssues):?><details class="clean" style="margin-top:18px"><summary><?=t('set.accepted_summary',['n'=>count($acceptedIssues)])?></summary><div class="inside checklist"><?php foreach($acceptedIssues as $ai):?><div class="checkitem info"><div><strong><?=h($ai['issue_title']?:t('set.accepted_default_title'))?></strong><div class="tiny"><?=h($ai['issue_detail'])?></div><div class="tiny"><?=t('set.accepted_on',['date'=>h(fiDate(substr((string)$ai['accepted_at'],0,10)))])?><?=!empty($ai['note'])?' · '.h(noteLabel((string)$ai['note'])):''?></div></div><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="restore_data_issue"><input type="hidden" name="issue_key" value="<?=h($ai['issue_key'])?>"><button class="btn2"><?=t('set.restore_to_check')?></button></form></div><?php endforeach;?></div></details><?php endif;?></section>
<section class="section panel" id="backup" data-tab="turva"><div class="sectionhead"><div><div class="eyebrow"><?=t('set.security_eyebrow')?></div><h2><?=t('set.backup_title')?></h2></div><div class="form-actions"><a class="btn2" href="?backup=db"><?=t('set.backup_sqlite')?></a><?php if(class_exists('ZipArchive')):?><a class="btn" href="?backup=full"><?=t('set.backup_full')?></a><?php endif;?></div></div><div class="backup-kinds"><div class="backup-kind"><strong><?=t('set.backup_sqlite')?></strong><span><?=t('set.backup_sqlite_help')?></span></div><div class="backup-kind"><strong><?=t('set.backup_full')?></strong><span><?=t('set.backup_full_help')?></span></div></div><p class="sub"><?=t('set.backup_contents',['ver'=>h((string)SCHEMA_VERSION)])?></p><p class="sub"><?=t('set.backup_auto_copy')?></p><?php if(!class_exists('ZipArchive')):?><div class="flash warn"><?=t('set.zip_missing')?></div><?php endif;?><details class="clean dangerzone"><summary><?=t('set.restore_summary')?></summary><div class="inside"><form method="post" enctype="multipart/form-data" onsubmit="return confirm('<?=addcslashes(t('set.restore_confirm'),"'\\")?>')"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="restore_db"><div class="grid grid3"><div><label><?=t('set.restore_file')?></label><input type="file" name="restore_file" accept=".sqlite3,.db,.zip,application/octet-stream,application/zip" required></div><div><label><?=t('set.restore_phrase')?></label><input name="restore_phrase" autocomplete="off" required></div><div><label style="margin-top:28px"><input type="checkbox" name="restore_check" value="1" required> <?=t('set.restore_check')?></label></div></div><div style="margin-top:10px"><label><input type="checkbox" name="restore_allow_older" value="1"> <?=t('set.restore_allow_older',['ver'=>h(APP_VERSION)])?></label><div class="tiny"><?=t('set.restore_allow_older_help')?></div></div><div class="form-actions"><button class="danger"><?=t('set.restore_btn')?></button></div></form></div></details></section>
<section class="section panel" id="suojaus" data-tab="turva"><h2><?=t('set.login_security_title')?></h2><div class="sec-status"><span class="badge <?=authHttps()?'okbadge':'warnbadge'?>"><?=t('set.https_badge',['state'=>authHttps()?t('set.https_on'):t('set.https_off')])?></span><span class="badge"><?=t('set.db_perms_badge',['perms'=>h(substr(sprintf('%o',fileperms(DB_FILE)),-3))])?></span><span class="badge"><?=t('set.session_badge')?></span></div><details class="clean sub-details"><summary><?=t('set.security_more_summary')?></summary><div class="inside"><p><?=t('set.security_text_1')?></p><p><?=t('set.security_text_2',['state'=>authHttps()?t('set.https_on'):t('set.https_off')])?></p><p><?=t('set.security_text_3',['perms'=>h(substr(sprintf('%o',fileperms(DB_FILE)),-3))])?></p><p><?=t('set.security_text_4')?></p></div></details>
<?php
$auditStats=$db->query('SELECT COUNT(*) total,COALESCE(MAX(id),0) last_id FROM auth_audit')->fetch();
$auditTotal=(int)$auditStats['total'];$auditPages=max(1,(int)ceil($auditTotal/AUTH_AUDIT_PAGE_SIZE));
$auditRequested=filter_var($_GET['audit_page']??1,FILTER_VALIDATE_INT);
$auditPage=min($auditPages,max(1,$auditRequested===false?1:$auditRequested));$auditOffset=($auditPage-1)*AUTH_AUDIT_PAGE_SIZE;
$auditSt=$db->prepare('SELECT a.event,a.created_at,a.actor_id,a.target_id,u.username actor,t.username target FROM auth_audit a LEFT JOIN auth_users u ON u.id=a.actor_id LEFT JOIN auth_users t ON t.id=a.target_id ORDER BY a.id DESC LIMIT ? OFFSET ?');
$auditSt->bindValue(1,AUTH_AUDIT_PAGE_SIZE,PDO::PARAM_INT);$auditSt->bindValue(2,$auditOffset,PDO::PARAM_INT);$auditSt->execute();$auditRows=$auditSt->fetchAll();
?>
<details class="clean" id="kayttajaloki" style="margin-top:18px" <?=isset($_GET['audit_page'])?'open':''?>><summary><?=t('set.audit_summary',['n'=>$auditTotal])?></summary><div class="inside">
<p class="tiny"><?=t('set.audit_intro',['n'=>AUTH_AUDIT_PAGE_SIZE])?> <?=$auditTotal?t('set.audit_showing',['from'=>$auditOffset+1,'to'=>$auditOffset+count($auditRows),'total'=>$auditTotal]):t('set.audit_empty')?> <?=t('set.audit_note')?></p>
<div class="auth-audit-rows">
<?php foreach($auditRows as $audit):?><div class="kv auth-audit-row"><span><?=h(date('d.m.Y H:i',strtotime($audit['created_at'])))?></span><span><?=h(($audit['actor']?:($audit['actor_id']?t('set.audit_deleted_user',['id'=>(int)$audit['actor_id']]):t('set.audit_setup'))).' · '.authEventLabel($audit['event']).($audit['target']?' · '.$audit['target']:($audit['target_id']?' · '.t('set.audit_user_id',['id'=>(int)$audit['target_id']]):'')))?></span></div><?php endforeach;?>
</div>
<?php if($auditPages>1):?><nav class="form-actions" aria-label="<?=t('set.audit_pages_aria')?>">
<?php if($auditPage>1):?><a class="btn2" href="?view=settings&audit_page=1#kayttajaloki"><?=t('set.audit_newest')?></a><a class="btn2" href="?view=settings&audit_page=<?=$auditPage-1?>#kayttajaloki"><?=t('set.audit_prev')?></a><?php endif;?>
<span class="tiny"><?=t('set.audit_page_of',['page'=>$auditPage,'pages'=>$auditPages])?></span>
<?php if($auditPage<$auditPages):?><a class="btn2" href="?view=settings&audit_page=<?=$auditPage+1?>#kayttajaloki"><?=t('set.audit_next')?></a><a class="btn2" href="?view=settings&audit_page=<?=$auditPages?>#kayttajaloki"><?=t('set.audit_oldest')?></a><?php endif;?>
</nav><?php endif;?>
<details class="clean" style="margin-top:16px"><summary><?=t('set.audit_clear_summary')?></summary><div class="inside">
<p class="tiny"><?=t('set.audit_clear_help')?></p>
<form method="post" class="clear-auth-audit-form"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="clear_auth_audit"><input type="hidden" name="audit_up_to" value="<?=(int)$auditStats['last_id']?>">
<label><?=t('set.audit_clear_scope')?></label><select name="audit_scope"><option value="login"><?=t('set.audit_scope_login')?></option><option value="all"><?=t('set.audit_scope_all')?></option></select>
<label style="margin-top:12px"><input type="checkbox" name="audit_confirm" value="1" required> <?=t('set.audit_clear_confirm')?></label>
<div class="form-actions"><button class="danger"><?=t('set.audit_clear_btn')?></button></div>
<p class="tiny"><?=t('set.audit_clear_note')?></p>
</form></div></details>
</div></details></section>
</div>
